    <fieldset>
    <legend>Campi codificati</legend>
    <p>
    <label>Pubblico</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Ogni</option>
      <option value="aud:a">per ragazzi, generale</option>
      <option value="aud:b">bambini (0-5)</option>
      <option value="aud:c">Primaria(5-8)</option>
      <option value="aud:d">ragazzi (9-14)</option>
      <option value="aud:e">Giovani</option>
      <option value="aud:k">Adulti, non fiction</option>
      <option value="aud:m">Adulti, qualsiasi</option>
      <option value="aud:u">Sconosciuto</option>
    </select>
    </p>
    <p>
    <label>Stampa</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >qualunque</option>
        <option value="Material-type:r">stampa (normale)</option>
        <option value="Material-type:d">stampa ingrandita</option>
        <option value="Material-type:e">formato tabloid</option>
        <option value="Material-type:f">Braille o altro sistema tattile</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">scritto a mano</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">stampa ridotta</option>
        <option value="Material-type:z">altra forma di materiale testuale</option>
    </select>
    </p>
    <p>
    <label>Pubblicazioni celebrative (indicazione)</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Ogni</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">dramma</option>
            <option value="Literature-Code:c">saggi</option>
            <option value="Literature-Code:d">humor, satira</option>
            <option value="Literature-Code:e">lettere</option>
            <option value="Literature-Code:f">racconti</option>
            <option value="Literature-Code:g">poesia</option>
            <option value="Literature-Code:h">discorsi, oratoria</option>
            <option value="Literature-Code:y">testo non letterario</option>
            <option value="Literature-Code:z">molteplici forme / altre forme</option>
    </select>
    </p>
        <p>
    <label>Biografia</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Ogni</option>
            <option value="Biography-code:y">Non una bibliografia</option>
            <option value="Biography-code:a">autobiografia</option>
            <option value="Biography-code:b">biografia</option>
            <option value="Biography-code:c">biografia collettiva</option>
            <option value="Biography-code:d">contiene dati biogr.</option>
    </select>
        </p>
        <p>
    <label>Illustrazione</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Ogni</option>
            <option value="Illustration-Code:a">illustrazioni</option>
            <option value="Illustration-Code:b">mappe</option>
            <option value="Illustration-Code:c">ritratti</option>
            <option value="Illustration-Code:d">carte</option>
            <option value="Illustration-Code:e">progetti</option>
            <option value="Illustration-Code:f">lastre</option>
            <option value="Illustration-Code:g">musica</option>
            <option value="Illustration-Code:h">facsimili</option>
            <option value="Illustration-Code:i">illustrazioni araldiche</option>
            <option value="Illustration-Code:j">alberi genealogici</option>
            <option value="Illustration-Code:k">formulari</option>
            <option value="Illustration-Code:l">esempi</option>
            <option value="Illustration-Code:m">registrazioni sonore</option>
            <option value="Illustration-Code:n">diapositive</option>
            <option value="Illustration-Code:o">miniature</option>
            <option value="Illustration-Code:y">nessuna illustrazione</option>
        </select>
        </p>
    <p>
    <label>Contenuto</label>
    <select name="limit" class="subtype">
      <option value="" >Ogni</option>
            <option value="ctype:a" >biografia</option>
            <option value="ctype:b" >catalogo</option>
            <option value="ctype:c" >indice</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >dizionario</option>
            <option value="ctype:f" >enciclopedia</option>
            <option value="ctype:g" >annuario, elenco</option>
            <option value="ctype:h" >descrizione di progetto</option>
            <option value="ctype:i" >statistiche</option>
            <option value="ctype:j" >materiale per l'auto-apprendimento</option>
            <option value="ctype:k" >brevetto</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >dissertazione o tesi</option>
            <option value="ctype:n" >leggi e legislazione</option>
            <option value="ctype:o" >tavola numerica</option>
            <option value="ctype:p" >report tecnico</option>
            <option value="ctype:q" >traccia d'esame</option>
            <option value="ctype:r" >recensioni / spogli della letteratura</option>
            <option value="ctype:s" >trattati</option>
            <option value="ctype:t" >cartoni animati o fumetti</option>
            <option value="ctype:z" >altro</option>
    </select>
        </p>
        <p>
    <label>Tipi di video</label>
    <select name="limit" class="subtype">
            <option value="">Ogni</option>
      <option value="Video-mt:a">film</option>
      <option value="Video-mt:b">proiezione visuale</option>
      <option value="Video-mt:c">registrazione video</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Seriali</legend><p>
    <p>
    <label>Tipologie di seriale</label>
    <select name="limit" class="subtype">
           <option value="">Ogni tipo</option>
           <option value="Type-Of-Serial:a">Periodico</option>
      <option value="Type-Of-Serial:b">Serie monografiche</option>
      <option value="Type-Of-Serial:c">Giornale</option>
      <option value="Type-Of-Serial:z">Altro</option>
    </select>
    </p>
    <p>
    <label>Periodicità</label>
    <select name="limit" class="subtype">
      <option value="">Ogni</option>
        <option value="Frequency-code:a">Giornalmente</option>
        <option value="Frequency-code:b">Bisettimanale</option>
        <option value="Frequency-code:c">Settimanale</option>
        <option value="Frequency-code:d">Bisettimanale</option>
        <option value="Frequency-code:e">Quindicinale</option>
        <option value="Frequency-code:f">Mensile</option>
        <option value="Frequency-code:g">Bimestrale</option>
        <option value="Frequency-code:h">Trimestrale</option>
        <option value="Frequency-code:i">Tre volte l'anno</option>
        <option value="Frequency-code:j">semestrale</option>
        <option value="Frequency-code:k">Annuale</option>
        <option value="Frequency-code:l">Biennale</option>
        <option value="Frequency-code:m">Triennale</option>
        <option value="Frequency-code:n">Tre volte a settimana</option>
        <option value="Frequency-code:o">Tre volte al mese</option>
        <option value="Frequency-code:u">Sconosciuto</option>
        <option value="Frequency-code:y">Senza periodicità</option>
        <option value="Frequency-code:i">Altro</option>
    </select>
    </p>
    <p>
    <label>Regolarità</label>
    <select name="limit" class="subtype">
            <option value="">Ogni regolarità</option>
        <option value="Regularity-code:u">Sconosciuto</option>
        <option value="Regularity-code:a">Regolare</option>
        <option value="Regularity-code:b">Irregolare normalizzato</option>
        <option value="Regularity-code:y">irregolare</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Immagine</legend><p>
    <select name="limit" class="subtype">
        <option value="">Ogni</option>
        <option value="Graphics-type:a">collage</option>
        <option value="Graphics-type:b">disegno</option>
        <option value="Graphics-type:c">dipinto</option>
        <option value="Graphics-type:d">riproduzione fotomeccanica</option>
        <option value="Graphics-type:e">negativo fotografico</option>
        <option value="Graphics-type:f">stampa fotografica</option>
        <option value="Graphics-type:h">immagine</option>
        <option value="Graphics-type:i">stampa</option>
        <option value="Graphics-type:k">disegno tecnico</option>
        <option value="Graphics-type:z">altro tipo di materiale grafico</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">qualunque</option>
            <option value="Graphics-support:a">tele</option>
            <option value="Graphics-support:b">cartoncino bristol</option>
            <option value="Graphics-support:c">cartoncini/disegni su cartoncino</option>
            <option value="Graphics-support:d">vetro</option>
            <option value="Graphics-support:j">plastico</option>
            <option value="Graphics-support:k">cartone compresso</option>
            <option value="Graphics-support:l">porcellana</option>
            <option value="Graphics-support:m">pietra</option>
            <option value="Graphics-support:n">legno</option>
            <option value="Graphics-support:u">sconosciuto</option>
            <option value="Graphics-support:v">misto</option>
            <option value="Graphics-support:e">sintetici</option>
            <option value="Graphics-support:f">pelle</option>
            <option value="Graphics-support:g">tessile</option>
            <option value="Graphics-support:h">metallo</option>
            <option value="Graphics-support:i">carta</option>
            <option value="Graphics-support:z">altri</option>
    </select>
        </p>
