    <fieldset>
    <legend>Kodede felter</legend>
    <p>
    <label>Publikum</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Enhver</option>
      <option value="aud:a">ungdom, generelt</option>
      <option value="aud:b">småbørn (0&ndash;5)</option>
      <option value="aud:c">Indskoling (5-8)</option>
      <option value="aud:d">børn (9&ndash;14)</option>
      <option value="aud:e">Ung voksen</option>
      <option value="aud:k">Voksen, alvorlig</option>
      <option value="aud:m">Voksen, generelt</option>
      <option value="aud:u">Ukendt</option>
    </select>
    </p>
    <p>
    <label>Udskriv</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >alle</option>
        <option value="Material-type:r">almindeligt tryk</option>
        <option value="Material-type:d">stor skrift</option>
        <option value="Material-type:e">avisformat</option>
        <option value="Material-type:f">Blindskrift eller måneskrift</option>
        <option value="Material-type:g">mikrotryk</option>
        <option value="Material-type:h">håndskrevet</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-tryk</option>
        <option value="Material-type:z">andre typer tekstmateriale</option>
    </select>
    </p>
    <p>
    <label>Festskrift for person</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Enhver</option>
            <option value="Literature-Code:a">skønlitteratur</option>
            <option value="Literature-Code:b">skuespil</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">humor, satire</option>
            <option value="Literature-Code:e">breve</option>
            <option value="Literature-Code:f">noveller</option>
            <option value="Literature-Code:g">poesi</option>
            <option value="Literature-Code:h">taler, lydmateriale</option>
            <option value="Literature-Code:y">ikke en litterær tekst</option>
            <option value="Literature-Code:z">flere/andre litterære former</option>
    </select>
    </p>
        <p>
    <label>Biografi</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Enhver</option>
            <option value="Biography-code:y">Ikke en biografi</option>
            <option value="Biography-code:a">selvbiografi</option>
            <option value="Biography-code:b">individuel biografi</option>
            <option value="Biography-code:c">samlebiografi</option>
            <option value="Biography-code:d">indeholder biografisk information</option>
    </select>
        </p>
        <p>
    <label>Illustration</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Enhver</option>
            <option value="Illustration-Code:a">illustrationer</option>
            <option value="Illustration-Code:b">kort</option>
            <option value="Illustration-Code:c">portrætter</option>
            <option value="Illustration-Code:d">diagrammer</option>
            <option value="Illustration-Code:e">grundrids</option>
            <option value="Illustration-Code:f">plader</option>
            <option value="Illustration-Code:g">musik</option>
            <option value="Illustration-Code:h">faksimiler</option>
            <option value="Illustration-Code:i">våbenskjold</option>
            <option value="Illustration-Code:j">slægtstavler</option>
            <option value="Illustration-Code:k">skemaer</option>
            <option value="Illustration-Code:l">prøver</option>
            <option value="Illustration-Code:m">lydoptagelse</option>
            <option value="Illustration-Code:n">transparenter</option>
            <option value="Illustration-Code:o">Illuminerede manuskripter</option>
            <option value="Illustration-Code:y">uden illustrationer</option>
        </select>
        </p>
    <p>
    <label>Indhold</label>
    <select name="limit" class="subtype">
      <option value="" >Enhver</option>
            <option value="ctype:a" >bibliografi</option>
            <option value="ctype:b" >samling</option>
            <option value="ctype:c" >register</option>
            <option value="ctype:d" >sammendrag</option>
            <option value="ctype:e" >ordbog</option>
            <option value="ctype:f" >leksikon</option>
            <option value="ctype:g" >mappe</option>
            <option value="ctype:h" >projektbeskrivelse</option>
            <option value="ctype:i" >statistik</option>
            <option value="ctype:j" >programmerede lærebøger</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >afhandling eller opgave</option>
            <option value="ctype:n" >lovtekster og lovgivning</option>
            <option value="ctype:o" >numerisk tabel</option>
            <option value="ctype:p" >teknisk rapport</option>
            <option value="ctype:q" >eksamensopgaver</option>
            <option value="ctype:r" >bogomtaler og kortlægning af litteratur</option>
            <option value="ctype:s" >traktater</option>
            <option value="ctype:t" >tegneserier</option>
            <option value="ctype:z" >andre</option>
    </select>
        </p>
        <p>
    <label>Videotyper</label>
    <select name="limit" class="subtype">
            <option value="">Enhver</option>
      <option value="Video-mt:a">bevægeligt billede</option>
      <option value="Video-mt:b">visuel projektion</option>
      <option value="Video-mt:c">videooptagelse</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Periodikaer</legend><p>
    <p>
    <label>Periodikatype</label>
    <select name="limit" class="subtype">
           <option value="">Enhver type</option>
           <option value="Type-Of-Serial:a">Tidsskrift og aviser</option>
      <option value="Type-Of-Serial:b">Monografiserie</option>
      <option value="Type-Of-Serial:c">Avis</option>
      <option value="Type-Of-Serial:z">Andre</option>
    </select>
    </p>
    <p>
    <label>Udgivelsesfrekvens</label>
    <select name="limit" class="subtype">
      <option value="">Enhver</option>
        <option value="Frequency-code:a">Dagligt</option>
        <option value="Frequency-code:b">To gange om ugen</option>
        <option value="Frequency-code:c">Ugentlig</option>
        <option value="Frequency-code:d">Hver anden uge</option>
        <option value="Frequency-code:e">To gange om måneden</option>
        <option value="Frequency-code:f">Månedlig</option>
        <option value="Frequency-code:g">Hver anden måned</option>
        <option value="Frequency-code:h">Kvartalsvis</option>
        <option value="Frequency-code:i">Tre gange om året</option>
        <option value="Frequency-code:j">Hvert halve år</option>
        <option value="Frequency-code:k">Årligt</option>
        <option value="Frequency-code:l">Hvert andet år</option>
        <option value="Frequency-code:m">Hvert tredje år</option>
        <option value="Frequency-code:n">Tre gange om ugen</option>
        <option value="Frequency-code:o">Tre gange om måneden</option>
        <option value="Frequency-code:u">Ukendt</option>
        <option value="Frequency-code:y">Helt uregelmæssigt</option>
        <option value="Frequency-code:i">Andre</option>
    </select>
    </p>
    <p>
    <label>Udgivelsesmønster</label>
    <select name="limit" class="subtype">
            <option value="">Ethvert udgivelsesmønster</option>
        <option value="Regularity-code:u">Ukendt</option>
        <option value="Regularity-code:a">Normal</option>
        <option value="Regularity-code:b">Normaliseret uregelmæssig</option>
        <option value="Regularity-code:y">uregelmæssig</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Billede</legend><p>
    <select name="limit" class="subtype">
        <option value="">Enhver</option>
        <option value="Graphics-type:a">collage</option>
        <option value="Graphics-type:b">tegning</option>
        <option value="Graphics-type:c">maleri</option>
        <option value="Graphics-type:d">fotomekanisk reproduktion</option>
        <option value="Graphics-type:e">fotonegativ</option>
        <option value="Graphics-type:f">fototryk</option>
        <option value="Graphics-type:h">billede</option>
        <option value="Graphics-type:i">tryk</option>
        <option value="Graphics-type:k">teknisk tegning</option>
        <option value="Graphics-type:z">andre grafiske formater som er uigennemtrængelige for lys</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">alle</option>
            <option value="Graphics-support:a">lærred</option>
            <option value="Graphics-support:b">Bristol-papir</option>
            <option value="Graphics-support:c">papbrædt/tegnebrædt</option>
            <option value="Graphics-support:d">glas</option>
            <option value="Graphics-support:j">gips</option>
            <option value="Graphics-support:k">spånplade</option>
            <option value="Graphics-support:l">porcelæn</option>
            <option value="Graphics-support:m">sten</option>
            <option value="Graphics-support:n">træ</option>
            <option value="Graphics-support:u">ukendt</option>
            <option value="Graphics-support:v">blandet samling</option>
            <option value="Graphics-support:e">syntetisk</option>
            <option value="Graphics-support:f">skind</option>
            <option value="Graphics-support:g">tekstil</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">papir</option>
            <option value="Graphics-support:z">andet</option>
    </select>
        </p>
