<select name="idx">
<!-- TMPL_IF NAME="selected" --><option value="kw" selected="selected">Keyword</option><!-- TMPL_ELSE --><option value="kw">Keyword</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,wrdl" selected="selected">Author</option><!-- TMPL_ELSE --><option value="au">Author</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಲೇಖಕ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ</option><!-- TMPL_ELSE --><option value="au,phr">&nbsp;&nbsp;&nbsp;&nbsp; ಲೇಖಕ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಸಂಸ್ಥೆಯ ಹೆಸರು</option><!-- TMPL_ELSE --><option value="cpn">&nbsp;&nbsp;&nbsp;&nbsp; ಸಂಸ್ಥೆಯ ಹೆಸರು</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಸಮ್ಮೇಳನದ ಹೆಸರು</option><!-- TMPL_ELSE --><option value="cfn">&nbsp;&nbsp;&nbsp;&nbsp; ಸಮ್ಮೇಳನದ ಹೆಸರು</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಸಂಸ್ಥೆಯ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- TMPL_ELSE --><option value="cpn,phr">&nbsp;&nbsp;&nbsp;&nbsp; ಸಂಸ್ಥೆಯ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಸಮ್ಮೇಳನದ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- TMPL_ELSE --><option value="cfn,phr">&nbsp;&nbsp;&nbsp;&nbsp; ಸಮ್ಮೇಳನದ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ವೈಯಕ್ತಿಕ ಹೆಸರು  </option><!-- TMPL_ELSE --><option value="pn">&nbsp;&nbsp;&nbsp;&nbsp; ವೈಯಕ್ತಿಕ ಹೆಸರು  </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ವೈಯಕ್ತಿಕ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- TMPL_ELSE --><option value="pn,phr">&nbsp;&nbsp;&nbsp;&nbsp; ವೈಯಕ್ತಿಕ ಹೆಸರು ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ln" selected="selected">Language</option><!-- TMPL_ELSE --><option value="ln">Language</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nt" selected="selected">Notes/Comments</option><!-- TMPL_ELSE --><option value="nt">Notes/Comments</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pb" selected="selected">Publisher</option><!-- TMPL_ELSE --><option value="pb">Publisher</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pl" selected="selected">Publisher Location</option><!-- TMPL_ELSE --><option value="pl">Publisher Location</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="yr" selected="selected">Publication Date (yyyy)</option><!-- TMPL_ELSE --><option value="yr">Publication Date (yyyy)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="acqdate" selected="selected">Acquisition Date (yyyy-mm-dd)</option><!-- TMPL_ELSE --><option value="acqdate">Acquisition Date (yyyy-mm-dd)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="sn" selected="selected">Standard Number</option><!-- TMPL_ELSE --><option value="sn">Standard Number</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nb" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ISBN </option><!-- TMPL_ELSE --><option value="nb">&nbsp;&nbsp;&nbsp;&nbsp; ISBN </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ns" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ISSN</option><!-- TMPL_ELSE --><option value="ns">&nbsp;&nbsp;&nbsp;&nbsp; ISSN</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="lcn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ಗಮನಿಸುವ ಸಂಖ್ಯೆ</option><!-- TMPL_ELSE --><option value="lcn,phr">&nbsp;&nbsp;&nbsp;&nbsp; ಗಮನಿಸುವ ಸಂಖ್ಯೆ</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su" selected="selected">Subject</option><!-- TMPL_ELSE --><option value="su">Subject</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;ವಿಷಯ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- TMPL_ELSE --><option value="su,phr">&nbsp;&nbsp;&nbsp;&nbsp;ವಿಷಯ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti" selected="selected">Title</option><!-- TMPL_ELSE --><option value="ti">Title</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;ಶೀರ್ಷಿಕೆ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ  </option><!-- TMPL_ELSE --><option value="ti,phr">&nbsp;&nbsp;&nbsp;&nbsp;ಶೀರ್ಷಿಕೆ ಅಭಿವ್ಯಕ್ತಿ ಯಂತೆ  </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="se" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;ಸರಣಿಯ  ಶೀರ್ಷಿಕೆ  </option><!-- TMPL_ELSE --><option value="se">&nbsp;&nbsp;&nbsp;&nbsp;ಸರಣಿಯ  ಶೀರ್ಷಿಕೆ  </option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="bc" selected="selected">Barcode</option><!-- TMPL_ELSE --><option value="bc">Barcode</option>
<!-- /TMPL_IF -->
</select>
