<select name="idx">
<!-- TMPL_IF NAME="selected" --><option value="kw" selected="selected">Keyword</option><!-- TMPL_ELSE --><option value="kw">Keyword</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,wrdl" selected="selected">Szerző</option><!-- TMPL_ELSE --><option value="au">Szerző</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Szerző (kifejezés)</option><!-- TMPL_ELSE --><option value="au,phr">&nbsp;&nbsp;&nbsp;&nbsp; Szerző (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Jogi személy neve</option><!-- TMPL_ELSE --><option value="cpn">&nbsp;&nbsp;&nbsp;&nbsp; Jogi személy neve</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Konferencia neve</option><!-- TMPL_ELSE --><option value="cfn">&nbsp;&nbsp;&nbsp;&nbsp; Konferencia neve</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Jogi személy neve (kifejezés)</option><!-- TMPL_ELSE --><option value="cpn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Jogi személy neve (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Konferencia neve (kifejezés)</option><!-- TMPL_ELSE --><option value="cfn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Konferencia neve (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Személy név</option><!-- TMPL_ELSE --><option value="pn">&nbsp;&nbsp;&nbsp;&nbsp; Személy név</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Személy név (kifejezés)</option><!-- TMPL_ELSE --><option value="pn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Személy név (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ln" selected="selected">Language</option><!-- TMPL_ELSE --><option value="ln">Language</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nt" selected="selected">Notes/Comments</option><!-- TMPL_ELSE --><option value="nt">Notes/Comments</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pb" selected="selected">Publisher</option><!-- TMPL_ELSE --><option value="pb">Publisher</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pl" selected="selected">Publisher Location</option><!-- TMPL_ELSE --><option value="pl">Publisher Location</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="yr" selected="selected">Publication Date (yyyy)</option><!-- TMPL_ELSE --><option value="yr">Publication Date (yyyy)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="acqdate" selected="selected">Beszerési dátum (éééé-hh-nn)</option><!-- TMPL_ELSE --><option value="acqdate">Beszerési dátum (éééé-hh-nn)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="sn" selected="selected">Standard Number</option><!-- TMPL_ELSE --><option value="sn">Standard Number</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nb" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ISBN</option><!-- TMPL_ELSE --><option value="nb">&nbsp;&nbsp;&nbsp;&nbsp; ISBN</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ns" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; ISSN</option><!-- TMPL_ELSE --><option value="ns">&nbsp;&nbsp;&nbsp;&nbsp; ISSN</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="lcn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Helyrajzi szám</option><!-- TMPL_ELSE --><option value="lcn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Helyrajzi szám</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su" selected="selected">Subject</option><!-- TMPL_ELSE --><option value="su">Subject</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Tárgya (kifejezés)</option><!-- TMPL_ELSE --><option value="su,phr">&nbsp;&nbsp;&nbsp;&nbsp; Tárgya (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti" selected="selected">Title</option><!-- TMPL_ELSE --><option value="ti">Title</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Cím (kifejezés)</option><!-- TMPL_ELSE --><option value="ti,phr">&nbsp;&nbsp;&nbsp;&nbsp; Cím (kifejezés)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="se" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Sorozat címe</option><!-- TMPL_ELSE --><option value="se">&nbsp;&nbsp;&nbsp;&nbsp; Sorozat címe</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="bc" selected="selected">Vonalkód</option><!-- TMPL_ELSE --><option value="bc">Vonalkód</option>
<!-- /TMPL_IF -->
</select>
