    <fieldset>
    <legend>الحقول المشفرة</legend>
    <p>
    <label>الجمهور</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >غير محدد</option>
      <option value="aud:a">الاحداث العامة</option>
      <option value="aud:b"> (قبل البدء (0-5</option>
      <option value="aud:c">الابتدائى(5-8)</option>
      <option value="aud:d">(أطفال (9-14</option>
      <option value="aud:e">الصغار الكبار</option>
      <option value="aud:k">الكبار ، خطيرة</option>
      <option value="aud:m">الكبار ، العام</option>
      <option value="aud:u">مجهول</option>
    </select>
    </p>
    <p>
    <label>اطبع</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" > غير محدد</option>
        <option value="Material-type:r">طباعة عاديه</option>
        <option value="Material-type:d">طباعة كبير</option>
        <option value="Material-type:e">شكل صحيفة</option>
        <option value="Material-type:f">الكتابة على طريقة برايل</option>
        <option value="Material-type:g">الصورة المجهرية</option>
        <option value="Material-type:h">خط اليد</option>
        <option value="Material-type:i">الوسائط المتعددة</option>
        <option value="Material-type:j">طباعة </option>
        <option value="Material-type:z">شكل آخر من أشكال المواد النصية</option>
    </select>
    </p>
    <p>
    <label>فشريف اند</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >غير محدد</option>
            <option value="Literature-Code:a">خيال</option>
            <option value="Literature-Code:b">دراما</option>
            <option value="Literature-Code:c">المقالات</option>
            <option value="Literature-Code:d">الفكاهه و  الهجاء</option>
            <option value="Literature-Code:e">الرسائل</option>
            <option value="Literature-Code:f">قصص قصيرة</option>
            <option value="Literature-Code:g">الشعر</option>
            <option value="Literature-Code:h">الخطب  و الخطابة</option>
            <option value="Literature-Code:y">ليس نصا أدبيا</option>
            <option value="Literature-Code:z">الكثير/ أشكال أدبية أخرى</option>
    </select>
    </p>
        <p>
    <label>السيرة </label>
        <select name="limit" class="subtype" size="1">
            <option value="">غير محدد</option>
            <option value="Biography-code:y">ليست سيرة ذاتية</option>
            <option value="Biography-code:a">سيرة ذاتيّة</option>
            <option value="Biography-code:b">السيرة الذاتية</option>
            <option value="Biography-code:c">السيره الجماعية</option>
            <option value="Biography-code:d">تتضمن بيان من المراجع</option>
    </select>
        </p>
        <p>
    <label>الايضاح</label>
        <select name="limit" class="subtype" size="1">
            <option value="">غير محدد</option>
            <option value="Illustration-Code:a">ايضاحات</option>
            <option value="Illustration-Code:b">الخرائط</option>
            <option value="Illustration-Code:c">صور</option>
            <option value="Illustration-Code:d">المخططات</option>
            <option value="Illustration-Code:e">خطط</option>
            <option value="Illustration-Code:f">لوحات</option>
            <option value="Illustration-Code:g">موسيقى</option>
            <option value="Illustration-Code:h">نسخ</option>
            <option value="Illustration-Code:i">الشعارات</option>
            <option value="Illustration-Code:j">جداول النسب</option>
            <option value="Illustration-Code:k">الاشكال</option>
            <option value="Illustration-Code:l">عينات</option>
            <option value="Illustration-Code:m">تسجيل الصوت</option>
            <option value="Illustration-Code:n">شفافيات</option>
            <option value="Illustration-Code:o"> انارات</option>
            <option value="Illustration-Code:y">بدون ايضاحات</option>
        </select>
        </p>
    <p>
    <label>محتوى</label>
    <select name="limit" class="subtype">
      <option value="" >غير محدد</option>
            <option value="ctype:a" >المراجع</option>
            <option value="ctype:b" >الدليل</option>
            <option value="ctype:c" >الفهرس</option>
            <option value="ctype:d" >ملخّص</option>
            <option value="ctype:e" >القاموس</option>
            <option value="ctype:f" >الموسوعة</option>
            <option value="ctype:g" >الملف</option>
            <option value="ctype:h" >وصف المشروع</option>
            <option value="ctype:i" >احصائيات</option>
            <option value="ctype:j" >الكتب المبرمجه</option>
            <option value="ctype:k" >براءه الاختراع</option>
            <option value="ctype:l" >قياسي</option>
            <option value="ctype:m" >اطروحات</option>
            <option value="ctype:n" >القوانين والتشريعات</option>
            <option value="ctype:o" >جدول رقمي</option>
            <option value="ctype:p" >التقرير التقن</option>
            <option value="ctype:q" >ورقة الاختبار</option>
            <option value="ctype:r" >التحقيقات الأدبية  / المراجع</option>
            <option value="ctype:s" >المعاهدات</option>
            <option value="ctype:t" >شرائط فكاهة أو كرتون    </option>
            <option value="ctype:z" >آخر</option>
    </select>
        </p>
        <p>
    <label>أنواع الفيديو</label>
    <select name="limit" class="subtype">
            <option value="">غير محدد</option>
      <option value="Video-mt:a">شريط صور</option>
      <option value="Video-mt:b">عرض بصري</option>
      <option value="Video-mt:c">تسجيل الفيديو</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>السلسلات </legend><p>
    <p>
    <label>صنف السلسلة</label>
    <select name="limit" class="subtype">
           <option value="">أي نوع</option>
           <option value="Type-Of-Serial:a">دوري</option>
      <option value="Type-Of-Serial:b">سلسلات مونوجرافية</option>
      <option value="Type-Of-Serial:c">صحيفة</option>
      <option value="Type-Of-Serial:z">اخرى</option>
    </select>
    </p>
    <p>
    <label>الدورية</label>
    <select name="limit" class="subtype">
      <option value="">غير محدد</option>
        <option value="Frequency-code:a">يوميا</option>
        <option value="Frequency-code:b">نصف أسبوعيّ</option>
        <option value="Frequency-code:c">أسبوعيّ</option>
        <option value="Frequency-code:d">نصف شهري</option>
        <option value="Frequency-code:e">نصف شهري</option>
        <option value="Frequency-code:f">شهريا</option>
        <option value="Frequency-code:g">كل شهرين</option>
        <option value="Frequency-code:h">فصليا</option>
        <option value="Frequency-code:i">ثلاث مرّات في السنة</option>
        <option value="Frequency-code:j">نصف سنوي</option>
        <option value="Frequency-code:k">السنوي</option>
        <option value="Frequency-code:l">نصف سنوي</option>
        <option value="Frequency-code:m">واقع كل ثلاث سنوات</option>
        <option value="Frequency-code:n">ثلاث مرّات في الأسبوع</option>
        <option value="Frequency-code:o">ثلاث مرّات في الشهر</option>
        <option value="Frequency-code:u">مجهول</option>
        <option value="Frequency-code:y"> غير دوري</option>
        <option value="Frequency-code:i">اخرى</option>
    </select>
    </p>
    <p>
    <label>إنتظام</label>
    <select name="limit" class="subtype">
            <option value="">أي إنتظام</option>
        <option value="Regularity-code:u">مجهول</option>
        <option value="Regularity-code:a">عادي</option>
        <option value="Regularity-code:b">غير نظامي مطبع </option>
        <option value="Regularity-code:y">غير نظامي</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>صورة</legend><p>
    <select name="limit" class="subtype">
        <option value="">غير محدد</option>
        <option value="Graphics-type:a">الفن التصويري</option>
        <option value="Graphics-type:b">الرسم</option>
        <option value="Graphics-type:c">رسم</option>
        <option value="Graphics-type:d">صور الاستنساخ الميكانيكي</option>
        <option value="Graphics-type:e">صور الاستنساخ </option>
        <option value="Graphics-type:f">طباعة الصور</option>
        <option value="Graphics-type:h">صورة</option>
        <option value="Graphics-type:i">طباعة</option>
        <option value="Graphics-type:k">الرسم الفني</option>
        <option value="Graphics-type:z">نوع اخر من الرسوم غير البيانية </option>
    </select>
    <select name="limit" class="subtype">
            <option value=""> غير محدد</option>
            <option value="Graphics-support:a">وعاء</option>
            <option value="Graphics-support:b">لوحة بريستول</option>
            <option value="Graphics-support:c">ورق المقوى / لوحة الايضاح </option>
            <option value="Graphics-support:d">زجاج</option>
            <option value="Graphics-support:j">لصقة</option>
            <option value="Graphics-support:k">اللوح المضغوط</option>
            <option value="Graphics-support:l">الخزف</option>
            <option value="Graphics-support:m">الحجارة</option>
            <option value="Graphics-support:n">الخشب</option>
            <option value="Graphics-support:u">مجهول</option>
            <option value="Graphics-support:v">مجموعات مختلطة</option>
            <option value="Graphics-support:e">المواد المصنعه</option>
            <option value="Graphics-support:f">مظهر</option>
            <option value="Graphics-support:g">المنسوج</option>
            <option value="Graphics-support:h">المعدن</option>
            <option value="Graphics-support:i">الورق</option>
            <option value="Graphics-support:z">الآخرون</option>
    </select>
        </p>
