    <fieldset>
    <legend>Coded fields</legend>
    <p>
    <label>Audience</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Any</option>
      <option value="aud:a">juvenil, jeneral</option>
      <option value="aud:b">pre-primaria (0-5)</option>
      <option value="aud:c">Primariu (5-8)</option>
      <option value="aud:d">labarik sira (9-14)</option>
      <option value="aud:e">Young Adult</option>
      <option value="aud:k">Adult, serious</option>
      <option value="aud:m">Adult, General</option>
      <option value="aud:u">Unknown</option>
    </select>
    </p>
    <p>
    <label>Print</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >any</option>
        <option value="Material-type:r">regular print</option>
        <option value="Material-type:d">large print</option>
        <option value="Material-type:e">formata jornal</option>
        <option value="Material-type:f">Braille or Moon script</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">hakerek ho liman</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-print</option>
        <option value="Material-type:z">other form of textual material</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Any</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">komik</option>
            <option value="Literature-Code:e">letra</option>
            <option value="Literature-Code:f">istoria badak</option>
            <option value="Literature-Code:g">poetry</option>
            <option value="Literature-Code:h">speeches, oratory</option>
            <option value="Literature-Code:y">not a literary text</option>
            <option value="Literature-Code:z">multiple/other lit. forms</option>
    </select>
    </p>
        <p>
    <label>Biography</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Any</option>
            <option value="Biography-code:y">Not a biography</option>
            <option value="Biography-code:a">autobiography</option>
            <option value="Biography-code:b">individual biography</option>
            <option value="Biography-code:c">collective biography</option>
            <option value="Biography-code:d">contains biogr. data</option>
    </select>
        </p>
        <p>
    <label>Illustration</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Any</option>
            <option value="Illustration-Code:a">ilas sira</option>
            <option value="Illustration-Code:b">mapo</option>
            <option value="Illustration-Code:c">portraits</option>
            <option value="Illustration-Code:d">charts</option>
            <option value="Illustration-Code:e">planu sira</option>
            <option value="Illustration-Code:f">plates</option>
            <option value="Illustration-Code:g">musika</option>
            <option value="Illustration-Code:h">faksimile</option>
            <option value="Illustration-Code:i">coats of arms</option>
            <option value="Illustration-Code:j">genealogical tables</option>
            <option value="Illustration-Code:k">formulariu sira</option>
            <option value="Illustration-Code:l">exemplu</option>
            <option value="Illustration-Code:m">sound recordings</option>
            <option value="Illustration-Code:n">transparencies</option>
            <option value="Illustration-Code:o">illuminations</option>
            <option value="Illustration-Code:y">no illustrations</option>
        </select>
        </p>
    <p>
    <label>Content</label>
    <select name="limit" class="subtype">
      <option value="" >Any</option>
            <option value="ctype:a" >bibliography</option>
            <option value="ctype:b" >katalogu</option>
            <option value="ctype:c" >indeks</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >disionariu</option>
            <option value="ctype:f" >ensiklopedia</option>
            <option value="ctype:g" >diretoriu</option>
            <option value="ctype:h" >deskrisaun projetu</option>
            <option value="ctype:i" >statistika</option>
            <option value="ctype:j" >programmed text books</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >dissertation or thesis</option>
            <option value="ctype:n" >lei sira</option>
            <option value="ctype:o" >numeric table</option>
            <option value="ctype:p" >relatoriu teknikal</option>
            <option value="ctype:q" >surat exame</option>
            <option value="ctype:r" >survei literatura/opinaun</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >cartoons or comic strips</option>
            <option value="ctype:z" >seluk</option>
    </select>
        </p>
        <p>
    <label>Video Types</label>
    <select name="limit" class="subtype">
            <option value="">Any</option>
      <option value="Video-mt:a">filme</option>
      <option value="Video-mt:b">visual projection</option>
      <option value="Video-mt:c">video recording</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Serial sira</legend><p>
    <p>
    <label>Tipu Revista</label>
    <select name="limit" class="subtype">
           <option value="">Any type</option>
           <option value="Type-Of-Serial:a">Revista</option>
      <option value="Type-Of-Serial:b">Monographical series</option>
      <option value="Type-Of-Serial:c">Jornal</option>
      <option value="Type-Of-Serial:z">Seluk</option>
    </select>
    </p>
    <p>
    <label>Periodicity</label>
    <select name="limit" class="subtype">
      <option value="">Any</option>
        <option value="Frequency-code:a">Loron loron</option>
        <option value="Frequency-code:b">Semiweekly</option>
        <option value="Frequency-code:c">Semana semana</option>
        <option value="Frequency-code:d">Biweekly</option>
        <option value="Frequency-code:e">Semimonthly</option>
        <option value="Frequency-code:f">Fulan fulan</option>
        <option value="Frequency-code:g">Bimonthly</option>
        <option value="Frequency-code:h">Quarterly</option>
        <option value="Frequency-code:i">Tinan ida, dala tolu</option>
        <option value="Frequency-code:j">Semiannual</option>
        <option value="Frequency-code:k">Annual</option>
        <option value="Frequency-code:l">Biannual</option>
        <option value="Frequency-code:m">Triennial</option>
        <option value="Frequency-code:n">Semana ida, dala tolu</option>
        <option value="Frequency-code:o">Fulan ida, dala tolu</option>
        <option value="Frequency-code:u">Unknown</option>
        <option value="Frequency-code:y">Without periodicity</option>
        <option value="Frequency-code:i">Seluk</option>
    </select>
    </p>
    <p>
    <label>Regularity</label>
    <select name="limit" class="subtype">
            <option value="">Any regularity</option>
        <option value="Regularity-code:u">Unknown</option>
        <option value="Regularity-code:a">Regular</option>
        <option value="Regularity-code:b">Normalised irregular</option>
        <option value="Regularity-code:y">irregular</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Pintura</legend><p>
    <select name="limit" class="subtype">
        <option value="">Any</option>
        <option value="Graphics-type:a">collage</option>
        <option value="Graphics-type:b">drawing</option>
        <option value="Graphics-type:c">painting</option>
        <option value="Graphics-type:d">photomechanical reproduction</option>
        <option value="Graphics-type:e">photonegative</option>
        <option value="Graphics-type:f">photoprint</option>
        <option value="Graphics-type:h">imagen</option>
        <option value="Graphics-type:i">print</option>
        <option value="Graphics-type:k">technical drawing</option>
        <option value="Graphics-type:z">other non-projected graphic type</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">any</option>
            <option value="Graphics-support:a">canvas</option>
            <option value="Graphics-support:b">bristol board</option>
            <option value="Graphics-support:c">cardboard/illustration board</option>
            <option value="Graphics-support:d">glass</option>
            <option value="Graphics-support:j">plaster</option>
            <option value="Graphics-support:k">hardboard</option>
            <option value="Graphics-support:l">porcelaine</option>
            <option value="Graphics-support:m">fatuk</option>
            <option value="Graphics-support:n">ai</option>
            <option value="Graphics-support:u">la hatene</option>
            <option value="Graphics-support:v">mixed collection</option>
            <option value="Graphics-support:e">synthetics</option>
            <option value="Graphics-support:f">skin</option>
            <option value="Graphics-support:g">textile</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">surat</option>
            <option value="Graphics-support:z">seluk tan</option>
    </select>
        </p>
