    <fieldset>
    <legend>Koda felt</legend>
    <p>
    <label>Målgruppe</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Alle</option>
      <option value="aud:a">ungdom, generelt</option>
      <option value="aud:b">småbarn (0&ndash;5)</option>
      <option value="aud:c">Primary (5-8)</option>
      <option value="aud:d">barn (9&ndash;14)</option>
      <option value="aud:e">Ung vaksen</option>
      <option value="aud:k">Vaksen, alvorleg</option>
      <option value="aud:m">Adult, General</option>
      <option value="aud:u">Ukjend</option>
    </select>
    </p>
    <p>
    <label>Skriv ut</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >any</option>
        <option value="Material-type:r">vanleg trykk</option>
        <option value="Material-type:d">storskrift</option>
        <option value="Material-type:e">avisformat</option>
        <option value="Material-type:f">Blindeskrift (Braille) eller Moon-skrift</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">handskrive</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-print</option>
        <option value="Material-type:z">andre typar tekstmateriale</option>
    </select>
    </p>
    <p>
    <label>Festskrift ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Alle</option>
            <option value="Literature-Code:a">skjønnlitteratur</option>
            <option value="Literature-Code:b">skodespel</option>
            <option value="Literature-Code:c">essay</option>
            <option value="Literature-Code:d">humor, satire</option>
            <option value="Literature-Code:e">brev</option>
            <option value="Literature-Code:f">noveller</option>
            <option value="Literature-Code:g">poesi</option>
            <option value="Literature-Code:h">taler, lydmateriale</option>
            <option value="Literature-Code:y">ikkje ein litterær tekst</option>
            <option value="Literature-Code:z">flerie eller andre litterære sjangrar</option>
    </select>
    </p>
        <p>
    <label>Biografi</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Alle</option>
            <option value="Biography-code:y">Ikkje ein biografi</option>
            <option value="Biography-code:a">sjølvbiografi</option>
            <option value="Biography-code:b">biografi om ein person</option>
            <option value="Biography-code:c">samlebiografi</option>
            <option value="Biography-code:d">inneheld biografisk informasjon</option>
    </select>
        </p>
        <p>
    <label>Illustrasjon</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Alle</option>
            <option value="Illustration-Code:a">illustrasjonar</option>
            <option value="Illustration-Code:b">kart</option>
            <option value="Illustration-Code:c">portrett</option>
            <option value="Illustration-Code:d">diagram</option>
            <option value="Illustration-Code:e">plans</option>
            <option value="Illustration-Code:f">plater</option>
            <option value="Illustration-Code:g">musikk</option>
            <option value="Illustration-Code:h">faksimilar</option>
            <option value="Illustration-Code:i">våpenskjold</option>
            <option value="Illustration-Code:j">slektstavler</option>
            <option value="Illustration-Code:k">skjema</option>
            <option value="Illustration-Code:l">utdrag</option>
            <option value="Illustration-Code:m">lydopptak</option>
            <option value="Illustration-Code:n">lysark</option>
            <option value="Illustration-Code:o">illuminerte skrift</option>
            <option value="Illustration-Code:y">utan illustrasjonar</option>
        </select>
        </p>
    <p>
    <label>Innhald</label>
    <select name="limit" class="subtype">
      <option value="" >Alle</option>
            <option value="ctype:a" >bibliografi</option>
            <option value="ctype:b" >katalog</option>
            <option value="ctype:c" >register</option>
            <option value="ctype:d" >samandrag</option>
            <option value="ctype:e" >ordbok</option>
            <option value="ctype:f" >leksikon</option>
            <option value="ctype:g" >mappe</option>
            <option value="ctype:h" >prosjektframstilling</option>
            <option value="ctype:i" >satistikk</option>
            <option value="ctype:j" >programmerte lærebøker</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >Avhandling eller oppgåve</option>
            <option value="ctype:n" >lover og lovtekstar</option>
            <option value="ctype:o" >numerisk tabell</option>
            <option value="ctype:p" >teknisk rapport</option>
            <option value="ctype:q" >eksamensoppgåver</option>
            <option value="ctype:r" >bokomtalar og kartlegging av litteratur</option>
            <option value="ctype:s" >traktatar</option>
            <option value="ctype:t" >teikneseriar</option>
            <option value="ctype:z" >andre</option>
    </select>
        </p>
        <p>
    <label>Videotypar</label>
    <select name="limit" class="subtype">
            <option value="">Alle</option>
      <option value="Video-mt:a">film</option>
      <option value="Video-mt:b">visuell projeksjon</option>
      <option value="Video-mt:c">videoopptak</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Periodika</legend><p>
    <p>
    <label>Periodikatype</label>
    <select name="limit" class="subtype">
           <option value="">Alle typar</option>
           <option value="Type-Of-Serial:a">Tidsskrift, aviser o.l.</option>
      <option value="Type-Of-Serial:b">Monografiserie</option>
      <option value="Type-Of-Serial:c">Avis</option>
      <option value="Type-Of-Serial:z">Anna</option>
    </select>
    </p>
    <p>
    <label>Periodisitet (oppgitt utgjevingsfrekvens)</label>
    <select name="limit" class="subtype">
      <option value="">Alle</option>
        <option value="Frequency-code:a">Dagleg</option>
        <option value="Frequency-code:b">To gongar i veka</option>
        <option value="Frequency-code:c">Kvar veke</option>
        <option value="Frequency-code:d">Annankvar veke</option>
        <option value="Frequency-code:e">To gongar i månaden</option>
        <option value="Frequency-code:f">Månadleg</option>
        <option value="Frequency-code:g">Annankvar månad</option>
        <option value="Frequency-code:h">Kvartalsvis</option>
        <option value="Frequency-code:i">Tre gongar i året</option>
        <option value="Frequency-code:j">Kvart halvår</option>
        <option value="Frequency-code:k">Årleg</option>
        <option value="Frequency-code:l">Annankvart år</option>
        <option value="Frequency-code:m">Kvart tredje år</option>
        <option value="Frequency-code:n">Tre gonger i veka</option>
        <option value="Frequency-code:o">Tre gonger i månaden</option>
        <option value="Frequency-code:u">Ukjend</option>
        <option value="Frequency-code:y">Fullstendig uregelmessig</option>
        <option value="Frequency-code:i">Anna</option>
    </select>
    </p>
    <p>
    <label>Regularitet (faktisk utgjevingsmønster)</label>
    <select name="limit" class="subtype">
            <option value="">Any regularity</option>
        <option value="Regularity-code:u">Ukjend</option>
        <option value="Regularity-code:a">Vanleg</option>
        <option value="Regularity-code:b">Normalisert uregelmessig</option>
        <option value="Regularity-code:y">uregelmessig</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Bilete</legend><p>
    <select name="limit" class="subtype">
        <option value="">Alle</option>
        <option value="Graphics-type:a">kollasj</option>
        <option value="Graphics-type:b">teikning</option>
        <option value="Graphics-type:c">måleri</option>
        <option value="Graphics-type:d">fotomekanisk reproduksjon</option>
        <option value="Graphics-type:e">biletnegativ</option>
        <option value="Graphics-type:f">photoprint</option>
        <option value="Graphics-type:h">bilete</option>
        <option value="Graphics-type:i">trykk</option>
        <option value="Graphics-type:k">teknisk teikning</option>
        <option value="Graphics-type:z">andre grafiske format som er ugjennomtrengelege for lys</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">any</option>
            <option value="Graphics-support:a">lerret</option>
            <option value="Graphics-support:b">Bristol-papir</option>
            <option value="Graphics-support:c">kartong/teiknebrett</option>
            <option value="Graphics-support:d">glas</option>
            <option value="Graphics-support:j">gips</option>
            <option value="Graphics-support:k">sponplate</option>
            <option value="Graphics-support:l">porselen</option>
            <option value="Graphics-support:m">stein</option>
            <option value="Graphics-support:n">tre</option>
            <option value="Graphics-support:u">ukjend</option>
            <option value="Graphics-support:v">blanda samlingar</option>
            <option value="Graphics-support:e">syntetisk</option>
            <option value="Graphics-support:f">skinn</option>
            <option value="Graphics-support:g">tekstil</option>
            <option value="Graphics-support:h">metall</option>
            <option value="Graphics-support:i">papir</option>
            <option value="Graphics-support:z">anna</option>
    </select>
        </p>
