<h5>系统设置</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">系统设置</a></li>
</ul>

<h5>基本参数</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">图书馆、分馆、群组</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds and budgets</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">货币和汇率</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">馆藏类型和借阅代码</a></li>
</ul>

<h5>读者和流通</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">读者类别</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">县市和乡镇</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">道路类型</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Patron attribute types</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Circulation and fines rules</a></li>
</ul>

<h5>馆藏目录</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">容许值</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">MARC 书目架构</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Koha 对应 MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">MARC 书目架构测试</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">权威记录类别</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">分类法来源</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">记录匹配规则</a></li>
</ul>

<h5>其他参数</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/stopwords.pl">停用字</a></li>
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 客户端目标</a></li>
</ul>
