<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">首页</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">馆藏目录</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">读者</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">采购</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">出纳</a> ||
<a href="/cgi-bin/koha/reports-home.pl">报表</a> ||
<a href="/cgi-bin/koha/admin-home.pl">参数</a> ||
<a href="/cgi-bin/koha/about.pl">关于 Koha</a> || 
帮助
</div>

</body>
</html>
