<h5>建立与执行产生报表</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">新增</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">使用储存</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">利用 SQL 新增</a></li>
</ul>
<h5>报表字典</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">显示字典</a></li>
</ul>