<h5>报表指南</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">报表指南</a></li>
	</ul>

<h5>统计精灵</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">采购</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">读者</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">馆藏目录</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">出纳</a></li>
	</ul>


	<h5>排行榜</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">借阅最热门馆藏的读者</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">最热门馆藏</a></li>
	</ul>
	
	<h5>未使用</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">没有借阅的读者</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">馆藏未检验</a></li>
	</ul>


	<h5>其他</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">馆藏遗失</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">依照馆藏类型编目</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">借阅依照读者类别排序</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">平均借阅时间</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Till Reconciliation</a></li>
	</ul>
