    <fieldset>
    <legend>Κωδικοποιημένα Πεδία</legend>
    <p>
    <label>Ακροατήριο</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Οποιοδήποτε</option>
      <option value="aud:a">Ανήλικος, γενικά</option>
      <option value="aud:b">Προ-στοιχειώδης (0-5)</option>
      <option value="aud:c">στοιχειώδης (5-8)</option>
      <option value="aud:d">Παιδιά (9-14)</option>
      <option value="aud:e">νεαρός ενήλικας</option>
      <option value="aud:k">ενήλικος, σοβαρός</option>
      <option value="aud:m">ενήλικος, γενικά</option>
      <option value="aud:u">άγνωστο</option>
    </select>
    </p>
    <p>
    <label>Εκτύπωση</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >οποιοδήποτε</option>
        <option value="Material-type:r">κανονικό κείμενο</option>
        <option value="Material-type:d">μεγεθυμένο κείμενο</option>
        <option value="Material-type:e">διάταξη εφημερίδας</option>
        <option value="Material-type:f">γραφή μπράιγ ή moon</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">χειρόγραφο</option>
        <option value="Material-type:i">πολυμέσα</option>
        <option value="Material-type:j">mini-print</option>
        <option value="Material-type:z">άλλος τύπος υλικού με κείμενο</option>
    </select>
    </p>
    <p>
    <label>Τιμητική έκδοση</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Οποιοδήποτε</option>
            <option value="Literature-Code:a">μυθιστόρημα</option>
            <option value="Literature-Code:b">θεατρικό έργο</option>
            <option value="Literature-Code:c">δοκίμια</option>
            <option value="Literature-Code:d">χιούμορ, σάτυρα</option>
            <option value="Literature-Code:e">γράμματα</option>
            <option value="Literature-Code:f">σύντομες ιστορίες</option>
            <option value="Literature-Code:g">ποίηση</option>
            <option value="Literature-Code:h">ομιλίες, ρητορική</option>
            <option value="Literature-Code:y">μη λογοτεχνικό κείμενο</option>
            <option value="Literature-Code:z">πολλαπλές/άλλες φόρμες λ.</option>
    </select>
    </p>
        <p>
    <label>Βιογραφία</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Οποιοδήποτε</option>
            <option value="Biography-code:y">δεν είναι βιογραφία</option>
            <option value="Biography-code:a">αυτοβιογραφία</option>
            <option value="Biography-code:b">ατομική βιογραφία</option>
            <option value="Biography-code:c">συλλογική βιογραφία</option>
            <option value="Biography-code:d">περιέχει βιογραφικά στοιχεία</option>
    </select>
        </p>
        <p>
    <label>Εικονογράφηση</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Οποιοδήποτε</option>
            <option value="Illustration-Code:a">εικονογραφήσεις</option>
            <option value="Illustration-Code:b">χάρτες</option>
            <option value="Illustration-Code:c">πορτραίτα</option>
            <option value="Illustration-Code:d">διαγράμματα</option>
            <option value="Illustration-Code:e">σχέδια</option>
            <option value="Illustration-Code:f">πίνακες</option>
            <option value="Illustration-Code:g">μουσική</option>
            <option value="Illustration-Code:h">πανομοιότυπα</option>
            <option value="Illustration-Code:i">θυρεοί</option>
            <option value="Illustration-Code:j">γενεαλογικοί πίνακες</option>
            <option value="Illustration-Code:k">φόρμες</option>
            <option value="Illustration-Code:l">δείγματα</option>
            <option value="Illustration-Code:m">ηχογραφήσεις</option>
            <option value="Illustration-Code:n">διαφάνειες</option>
            <option value="Illustration-Code:o">φωτισμοί</option>
            <option value="Illustration-Code:y">χωρίς εικονογράφηση</option>
        </select>
        </p>
    <p>
    <label>Περιεχόμενο</label>
    <select name="limit" class="subtype">
      <option value="" >Οποιοδήποτε</option>
            <option value="ctype:a" >βιβλιογραφία</option>
            <option value="ctype:b" >κατάλογος</option>
            <option value="ctype:c" >ευρετήριο</option>
            <option value="ctype:d" >περίληψη</option>
            <option value="ctype:e" >λεξικό</option>
            <option value="ctype:f" >εγκυκλοπαίδεια</option>
            <option value="ctype:g" >κατάλογος</option>
            <option value="ctype:h" >περιγραφή έργου</option>
            <option value="ctype:i" >στατιστικά στοιχεία</option>
            <option value="ctype:j" >προγραμματισμένα βιβλία</option>
            <option value="ctype:k" >ευρεσιτεχνία</option>
            <option value="ctype:l" >πρότυπο</option>
            <option value="ctype:m" >διπλωματική εργασία ή διατριβή</option>
            <option value="ctype:n" >νόμοι και νομοθεσία</option>
            <option value="ctype:o" >αριθμητικός πίνακας</option>
            <option value="ctype:p" >τεχνική αναφορά</option>
            <option value="ctype:q" >έγγραφα εξετάσεων</option>
            <option value="ctype:r" >λογοτεχνικές έρευνες/κριτικές</option>
            <option value="ctype:s" >συμφωνίες</option>
            <option value="ctype:t" >γελιογραφίες ή σκίτσα</option>
            <option value="ctype:z" >άλλο</option>
    </select>
        </p>
        <p>
    <label>Τύποι Βίντεο</label>
    <select name="limit" class="subtype">
            <option value="">Οποιοδήποτε</option>
      <option value="Video-mt:a">κινηματογραφική ταινία</option>
      <option value="Video-mt:b">oπτική προβολή</option>
      <option value="Video-mt:c">εγγραφή video</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Περιοδικές Εκδόσεις</legend><p>
    <p>
    <label>Τύπος Περιοδικής Έκδοσης</label>
    <select name="limit" class="subtype">
           <option value="">Οποιοσδήποτε τύπος</option>
           <option value="Type-Of-Serial:a">Περιοδικό</option>
      <option value="Type-Of-Serial:b">Μονογραφικές σειρές</option>
      <option value="Type-Of-Serial:c">Εφημερίδα</option>
      <option value="Type-Of-Serial:z">Άλλο</option>
    </select>
    </p>
    <p>
    <label>Περιοδικότητα</label>
    <select name="limit" class="subtype">
      <option value="">Οποιοδήποτε</option>
        <option value="Frequency-code:a">Καθημερινό</option>
        <option value="Frequency-code:b">Δύο φορές την εβδομάδα</option>
        <option value="Frequency-code:c">Εβδομαδιαίο</option>
        <option value="Frequency-code:d">Δύο φορές την εβδομάδα</option>
        <option value="Frequency-code:e">Δεκαπενθήμερο</option>
        <option value="Frequency-code:f">Μηνιαίο</option>
        <option value="Frequency-code:g">Διμηνιαίο</option>
        <option value="Frequency-code:h">Τριμηνιαίο</option>
        <option value="Frequency-code:i">Τρεις φορές το χρόνο</option>
        <option value="Frequency-code:j">Εξαμηνιαίο</option>
        <option value="Frequency-code:k">Ετήσιο</option>
        <option value="Frequency-code:l">Εξαμηνιαίο</option>
        <option value="Frequency-code:m">Τριετές</option>
        <option value="Frequency-code:n">Τρεις φορές την εβδομάδα</option>
        <option value="Frequency-code:o">Τρεις φορές το μήνα</option>
        <option value="Frequency-code:u">άγνωστο</option>
        <option value="Frequency-code:y">Χωρίς περιοδικότητα</option>
        <option value="Frequency-code:i">Άλλο</option>
    </select>
    </p>
    <p>
    <label>Κανονικότητα</label>
    <select name="limit" class="subtype">
            <option value="">Οποιαδήποτε τακτικότητα</option>
        <option value="Regularity-code:u">άγνωστο</option>
        <option value="Regularity-code:a">Τακτικό</option>
        <option value="Regularity-code:b">Ανώμαλη ομαλοποίηση</option>
        <option value="Regularity-code:y">Μη τακτικό</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Εικόνα</legend><p>
    <select name="limit" class="subtype">
        <option value="">Οποιοδήποτε</option>
        <option value="Graphics-type:a">κολάζ</option>
        <option value="Graphics-type:b">σχέδιο</option>
        <option value="Graphics-type:c">ζωγραφική</option>
        <option value="Graphics-type:d">φωτομηχανική αναπαραγωγή</option>
        <option value="Graphics-type:e">φωτοαρνητικό</option>
        <option value="Graphics-type:f">φωτοαντίτυπο</option>
        <option value="Graphics-type:h">εικόνα</option>
        <option value="Graphics-type:i">έντυπο</option>
        <option value="Graphics-type:k">τεχνικό σχέδιο</option>
        <option value="Graphics-type:z">άλλος μη-προβαλλόμενος τύπος γραφικών</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">οποιοδήποτε</option>
            <option value="Graphics-support:a">καμβάς</option>
            <option value="Graphics-support:b">bristol board</option>
            <option value="Graphics-support:c">χαρτόνι/πίνακας εικονογράφησης</option>
            <option value="Graphics-support:d">γυάλινο</option>
            <option value="Graphics-support:j">γύψινο</option>
            <option value="Graphics-support:k">σανίδα</option>
            <option value="Graphics-support:l">πορσελάνη</option>
            <option value="Graphics-support:m">πέτρα</option>
            <option value="Graphics-support:n">ξύλινο</option>
            <option value="Graphics-support:u">άγνωστο</option>
            <option value="Graphics-support:v">ανάμεικτη συλλογή</option>
            <option value="Graphics-support:e">συνθετικό</option>
            <option value="Graphics-support:f">δερμάτινο</option>
            <option value="Graphics-support:g">υφαντό</option>
            <option value="Graphics-support:h">μεταλλικό</option>
            <option value="Graphics-support:i">χαρτί</option>
            <option value="Graphics-support:z">άλλοι</option>
    </select>
        </p>
