    <fieldset>
    <legend>Campos Codificados</legend>
    <p>
    <label>Audiência</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Qualquer</option>
      <option value="aud:a">juvenil, geral</option>
      <option value="aud:b">pré-primário (0-5)</option>
      <option value="aud:c">Primary (5-8)</option>
      <option value="aud:d">crianças (9-14)</option>
      <option value="aud:e">Jovem Adulto</option>
      <option value="aud:k">Adult, serious</option>
      <option value="aud:m">Adultos, Geral</option>
      <option value="aud:u">Desconhecido</option>
    </select>
    </p>
    <p>
    <label>Imprimir</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >qualquer</option>
        <option value="Material-type:r">Impressão normal</option>
        <option value="Material-type:d">grande impressão</option>
        <option value="Material-type:e">formato jornal</option>
        <option value="Material-type:f">Braille or Moon script</option>
        <option value="Material-type:g">microimpressão</option>
        <option value="Material-type:h">escrito á mão</option>
        <option value="Material-type:i">multimédia</option>
        <option value="Material-type:j">mini-impressão</option>
        <option value="Material-type:z">outra forma de material textual</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Qualquer</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">humor, sátira</option>
            <option value="Literature-Code:e">cartas</option>
            <option value="Literature-Code:f">histórias curtas</option>
            <option value="Literature-Code:g">poesia</option>
            <option value="Literature-Code:h">discursos, oratório</option>
            <option value="Literature-Code:y">não é texto literário</option>
            <option value="Literature-Code:z">outras formas lit.</option>
    </select>
    </p>
        <p>
    <label>Biografia</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Qualquer</option>
            <option value="Biography-code:y">Não é uma biografia</option>
            <option value="Biography-code:a">autobiografia</option>
            <option value="Biography-code:b">biografia pessoal</option>
            <option value="Biography-code:c">biografia colectiva</option>
            <option value="Biography-code:d">contains biogr. data</option>
    </select>
        </p>
        <p>
    <label>Ilustração</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Qualquer</option>
            <option value="Illustration-Code:a">ilustrações</option>
            <option value="Illustration-Code:b">mapas</option>
            <option value="Illustration-Code:c">retratos</option>
            <option value="Illustration-Code:d">Gráficos</option>
            <option value="Illustration-Code:e">planos</option>
            <option value="Illustration-Code:f">plates</option>
            <option value="Illustration-Code:g">música</option>
            <option value="Illustration-Code:h">facsimiles</option>
            <option value="Illustration-Code:i">brasão</option>
            <option value="Illustration-Code:j">tabela genealógica</option>
            <option value="Illustration-Code:k">forms</option>
            <option value="Illustration-Code:l">exemplos</option>
            <option value="Illustration-Code:m">sound recordings</option>
            <option value="Illustration-Code:n">transparencias</option>
            <option value="Illustration-Code:o">iluminações</option>
            <option value="Illustration-Code:y">nehuma ilustração</option>
        </select>
        </p>
    <p>
    <label>Content</label>
    <select name="limit" class="subtype">
      <option value="" >Qualquer</option>
            <option value="ctype:a" >bibliografia</option>
            <option value="ctype:b" >catálogo</option>
            <option value="ctype:c" >index</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >dictionary</option>
            <option value="ctype:f" >enciclopedia</option>
            <option value="ctype:g" >directório</option>
            <option value="ctype:h" >project description</option>
            <option value="ctype:i" >estatisticas</option>
            <option value="ctype:j" >livros de texto programados</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >dissertação ou tese</option>
            <option value="ctype:n" >leis e legislação</option>
            <option value="ctype:o" >tabela numerica</option>
            <option value="ctype:p" >demonstração técnica</option>
            <option value="ctype:q" >folha de exame</option>
            <option value="ctype:r" >literature surveys/reviews</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >banda desenhada/desenhos animados</option>
            <option value="ctype:z" >other</option>
    </select>
        </p>
        <p>
    <label>Video Types</label>
    <select name="limit" class="subtype">
            <option value="">Qualquer</option>
      <option value="Video-mt:a">filme</option>
      <option value="Video-mt:b">projecção visual</option>
      <option value="Video-mt:c">gravação em video</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Serials</legend><p>
    <p>
    <label>Serial Type</label>
    <select name="limit" class="subtype">
           <option value="">Any type</option>
           <option value="Type-Of-Serial:a">Periódico</option>
      <option value="Type-Of-Serial:b">Monographical series</option>
      <option value="Type-Of-Serial:c">Jornal</option>
      <option value="Type-Of-Serial:z">Outro</option>
    </select>
    </p>
    <p>
    <label>Periodicidade</label>
    <select name="limit" class="subtype">
      <option value="">Qualquer</option>
        <option value="Frequency-code:a">Daily</option>
        <option value="Frequency-code:b">Semissemanalmente</option>
        <option value="Frequency-code:c">Weekly</option>
        <option value="Frequency-code:d">Biweekly</option>
        <option value="Frequency-code:e">Semimonthly</option>
        <option value="Frequency-code:f">Monthly</option>
        <option value="Frequency-code:g">Bimonthly</option>
        <option value="Frequency-code:h">Quarterly</option>
        <option value="Frequency-code:i">Three times a year</option>
        <option value="Frequency-code:j">Semianual</option>
        <option value="Frequency-code:k">Anual</option>
        <option value="Frequency-code:l">Bianual</option>
        <option value="Frequency-code:m">Trienial</option>
        <option value="Frequency-code:n">Three times a week</option>
        <option value="Frequency-code:o">Three times a month</option>
        <option value="Frequency-code:u">Desconhecido</option>
        <option value="Frequency-code:y">Sem periodicidade</option>
        <option value="Frequency-code:i">Outro</option>
    </select>
    </p>
    <p>
    <label>Regularidade</label>
    <select name="limit" class="subtype">
            <option value="">Qualquer Regularidade</option>
        <option value="Regularity-code:u">Desconhecido</option>
        <option value="Regularity-code:a">Regular</option>
        <option value="Regularity-code:b">Irregular normalizado</option>
        <option value="Regularity-code:y">irregular</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Fotografia</legend><p>
    <select name="limit" class="subtype">
        <option value="">Qualquer</option>
        <option value="Graphics-type:a">montagem</option>
        <option value="Graphics-type:b">desenho</option>
        <option value="Graphics-type:c">painting</option>
        <option value="Graphics-type:d">reprodução fotomecânica</option>
        <option value="Graphics-type:e">fotonegativo</option>
        <option value="Graphics-type:f">fotoimpressão</option>
        <option value="Graphics-type:h">imagem</option>
        <option value="Graphics-type:i">print</option>
        <option value="Graphics-type:k">desenho técnico</option>
        <option value="Graphics-type:z">outro tipo de gráfico não projectado</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">qualquer</option>
            <option value="Graphics-support:a">canvas</option>
            <option value="Graphics-support:b">quadro de bristol</option>
            <option value="Graphics-support:c">cavalete</option>
            <option value="Graphics-support:d">vidro</option>
            <option value="Graphics-support:j">reboco</option>
            <option value="Graphics-support:k">Quadro rigido</option>
            <option value="Graphics-support:l">porcelana</option>
            <option value="Graphics-support:m">pedra</option>
            <option value="Graphics-support:n">madeira</option>
            <option value="Graphics-support:u">desconhecido</option>
            <option value="Graphics-support:v">mixed collection</option>
            <option value="Graphics-support:e">sinteticos</option>
            <option value="Graphics-support:f">skin</option>
            <option value="Graphics-support:g">têxtil</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">papel</option>
            <option value="Graphics-support:z">others</option>
    </select>
        </p>
