<h5>系統偏好</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">系統偏好</a></li>
</ul>

<h5>基本參數</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">圖書館、分館、群組</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds and budgets</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">貨幣和匯率</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">館藏型式和借閱代碼管理</a></li>
</ul>

<h5>讀者和流通</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">讀者類別</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">縣市和鄉鎮</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">道路型式</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Patron attribute types</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Circulation and fines rules</a></li>
</ul>

<h5>館藏目錄</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">容許值</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">MARC 書目架構</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Koha 對應 MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">MARC 書目架構測試</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">權威記錄類別</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">分類法來源</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">書目記錄對應條件</a></li>
</ul>

<h5>其他參數</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/stopwords.pl">停用字</a></li>
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 主機</a></li>
</ul>
