<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">首頁</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">館藏目錄</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">讀者</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">採訪</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">流通</a> ||
<a href="/cgi-bin/koha/reports-home.pl">報表</a> ||
<a href="/cgi-bin/koha/admin-home.pl">參數</a> ||
<a href="/cgi-bin/koha/about.pl">關於 Koha</a> || 
說明
</div>

</body>
</html>
