<h5>建立與執行產生報表</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">新增</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">使用儲存</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">利用 SQL 新增</a></li>
</ul>
<h5>報表字典</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">顯示字典</a></li>
</ul>