<h5>產生報表</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">產生報表</a></li>
	</ul>

<h5>統計精靈</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">採訪</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">讀者</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">館藏目錄</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">流通</a></li>
	</ul>


	<h5>排行榜</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">借閱最熱門讀者</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">借閱最熱門館藏</a></li>
	</ul>
	
	<h5>沒有使用</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">沒有借閱的讀者</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">館藏無法預約</a></li>
	</ul>


	<h5>其他</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">館藏遺失</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">館藏目錄依照館藏型式</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">借閱依照讀者類別排序</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">平均借閱時間</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Till Reconciliation</a></li>
	</ul>
