    <fieldset>
    <legend>Campos codificados</legend>
    <p>
    <label>Audiencia</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Cualquier</option>
      <option value="aud:a">juvenil, general</option>
      <option value="aud:b">pre-primaria (0-5)</option>
      <option value="aud:c">Primaria (5-8)</option>
      <option value="aud:d">ni&ntilde;os (9-14)</option>
      <option value="aud:e">Jóvenes Adultos</option>
      <option value="aud:k">Adulto, serio</option>
      <option value="aud:m">Adulto, General</option>
      <option value="aud:u">Desconocido</option>
    </select>
    </p>
    <p>
    <label>Imprimir</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >Cualquiera</option>
        <option value="Material-type:r">Impresi&oacute;n regular</option>
        <option value="Material-type:d">Letra grande</option>
        <option value="Material-type:e">formato de per&iacute;odico</option>
        <option value="Material-type:f">Braille o script Moon</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">escrito a mano</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-print</option>
        <option value="Material-type:z">otra forma de material textual</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Cualquier</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">humor, s&aacute;tira</option>
            <option value="Literature-Code:e">cartas</option>
            <option value="Literature-Code:f">historias cortas</option>
            <option value="Literature-Code:g">poes&iacute;a</option>
            <option value="Literature-Code:h">Discursos, oratorio</option>
            <option value="Literature-Code:y">no es un texto literario</option>
            <option value="Literature-Code:z">formularios multiples/otra lit.</option>
    </select>
    </p>
        <p>
    <label>Bibliograf&iacute;a</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Cualquier</option>
            <option value="Biography-code:y">No es una biograf&iacute;a</option>
            <option value="Biography-code:a">Autobiograf&iacute;a</option>
            <option value="Biography-code:b">biograf&iacute;a individual</option>
            <option value="Biography-code:c">biograf&iacute;a colectiva</option>
            <option value="Biography-code:d">contiene datos biograficos</option>
    </select>
        </p>
        <p>
    <label>Ilustraci&oacute;n</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Cualquier</option>
            <option value="Illustration-Code:a">ilustraciones</option>
            <option value="Illustration-Code:b">mapas</option>
            <option value="Illustration-Code:c">retratos</option>
            <option value="Illustration-Code:d">cartas</option>
            <option value="Illustration-Code:e">Planes</option>
            <option value="Illustration-Code:f">plates</option>
            <option value="Illustration-Code:g">m&uacute;sica</option>
            <option value="Illustration-Code:h">facs&iacute;miles</option>
            <option value="Illustration-Code:i">Escudos de armas</option>
            <option value="Illustration-Code:j">Tablas geneal&oacute;gicas</option>
            <option value="Illustration-Code:k">forms</option>
            <option value="Illustration-Code:l">ejemplos</option>
            <option value="Illustration-Code:m">sound recordings</option>
            <option value="Illustration-Code:n">transparencias</option>
            <option value="Illustration-Code:o">iluminaciones</option>
            <option value="Illustration-Code:y">sin ilustraciones</option>
        </select>
        </p>
    <p>
    <label>Content</label>
    <select name="limit" class="subtype">
      <option value="" >Cualquier</option>
            <option value="ctype:a" >bibliografia</option>
            <option value="ctype:b" >cat&aacute;logo</option>
            <option value="ctype:c" >index</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >dictionary</option>
            <option value="ctype:f" >enciclopedia</option>
            <option value="ctype:g" >directorio</option>
            <option value="ctype:h" >project description</option>
            <option value="ctype:i" >estad&iacute;sticas</option>
            <option value="ctype:j" >Libros de texto programados</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >estandar</option>
            <option value="ctype:m" >Disertaci&oacute;n o tesis</option>
            <option value="ctype:n" >leyes y legislaci&oacute;n</option>
            <option value="ctype:o" >tabla num&eacute;rica</option>
            <option value="ctype:p" >informe t&eacute;cnico</option>
            <option value="ctype:q" >Prueba de examen</option>
            <option value="ctype:r" >literatura encuestas y ex&aacute;menes</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >historietas o c&oacute;mics</option>
            <option value="ctype:z" >other</option>
    </select>
        </p>
        <p>
    <label>Video Types</label>
    <select name="limit" class="subtype">
            <option value="">Cualquier</option>
      <option value="Video-mt:a">cine</option>
      <option value="Video-mt:b">Proyecci&oacute;n visual</option>
      <option value="Video-mt:c">grabaci&oacute;n de v&iacute;deo</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Serials</legend><p>
    <p>
    <label>Serial Type</label>
    <select name="limit" class="subtype">
           <option value="">Any type</option>
           <option value="Type-Of-Serial:a">Peri&oacute;dico</option>
      <option value="Type-Of-Serial:b">Series monogr&aacute;ficas</option>
      <option value="Type-Of-Serial:c">Periodico</option>
      <option value="Type-Of-Serial:z">Otro</option>
    </select>
    </p>
    <p>
    <label>Periodicidad</label>
    <select name="limit" class="subtype">
      <option value="">Cualquier</option>
        <option value="Frequency-code:a">Daily</option>
        <option value="Frequency-code:b">Semanal</option>
        <option value="Frequency-code:c">Weekly</option>
        <option value="Frequency-code:d">Biweekly</option>
        <option value="Frequency-code:e">Semimonthly</option>
        <option value="Frequency-code:f">Monthly</option>
        <option value="Frequency-code:g">Bimonthly</option>
        <option value="Frequency-code:h">Quarterly</option>
        <option value="Frequency-code:i">Tres veces al a&ntilde;o</option>
        <option value="Frequency-code:j">Semestral</option>
        <option value="Frequency-code:k">Anual</option>
        <option value="Frequency-code:l">Bianual</option>
        <option value="Frequency-code:m">Trienal</option>
        <option value="Frequency-code:n">Tres veces a la semana</option>
        <option value="Frequency-code:o">Tres veces al mes</option>
        <option value="Frequency-code:u">Desconocido</option>
        <option value="Frequency-code:y">Sin periodicidad</option>
        <option value="Frequency-code:i">Otro</option>
    </select>
    </p>
    <p>
    <label>Regularidad</label>
    <select name="limit" class="subtype">
            <option value="">Cualquier regularidad</option>
        <option value="Regularity-code:u">Desconocido</option>
        <option value="Regularity-code:a">Regular</option>
        <option value="Regularity-code:b">Normalizado irregular</option>
        <option value="Regularity-code:y">irregular</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Imagen</legend><p>
    <select name="limit" class="subtype">
        <option value="">Cualquier</option>
        <option value="Graphics-type:a">collage</option>
        <option value="Graphics-type:b">dibujo</option>
        <option value="Graphics-type:c">painting</option>
        <option value="Graphics-type:d">Reproducci&oacute;n fotomec&aacute;nica</option>
        <option value="Graphics-type:e">negativo fotogr&aacute;fico</option>
        <option value="Graphics-type:f">foto</option>
        <option value="Graphics-type:h">imagen</option>
        <option value="Graphics-type:i">print</option>
        <option value="Graphics-type:k">dibujo t&eacute;cnico</option>
        <option value="Graphics-type:z">otros tipos de gr&aacute;ficos no proyectados</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">Cualquiera</option>
            <option value="Graphics-support:a">lienzo</option>
            <option value="Graphics-support:b">Barco de Bristol</option>
            <option value="Graphics-support:c">cart&oacute;n/ilustraci&oacute;n</option>
            <option value="Graphics-support:d">cristal</option>
            <option value="Graphics-support:j">yeso</option>
            <option value="Graphics-support:k">Tabla base</option>
            <option value="Graphics-support:l">porcelana</option>
            <option value="Graphics-support:m">piedra</option>
            <option value="Graphics-support:n">madera</option>
            <option value="Graphics-support:u">desconocido</option>
            <option value="Graphics-support:v">mixed collection</option>
            <option value="Graphics-support:e">Sint%eacute;ticos</option>
            <option value="Graphics-support:f">skin</option>
            <option value="Graphics-support:g">textil</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">papel</option>
            <option value="Graphics-support:z">others</option>
    </select>
        </p>
