<h5>Construire et exécuter des rapports</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">Construire nouveau</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">Rapports sauvegardés</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">Créer à partir de SQL</a></li>
</ul>
<h5>Dictionnaire des rapports</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">Voir dictionnaire</a></li>
</ul>