<div id="navmenu"><ul id="navmenulist">
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Format</a></li>
	<li><a href="/cgi-bin/koha/labels/label-templates.pl">Modèles</a></li>
	<li><a href="/cgi-bin/koha/labels/label-profiles.pl">Profils d'imprimante</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=labels">Gérer les lots de traitement</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=patroncards">Gérer les lots de cartes adhérents</a></li>
</ul>
</div>
