<h5>Rapports</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Rapports</a></li>
	</ul>

<h5>Assistant statistiques</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Acquisitions</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Adhérents</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catalogue</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulation</a></li>
	</ul>


	<h5>Les palmarès</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Adhérents empruntants le plus</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Documents les plus empruntés</a></li>
	</ul>
	
	<h5>Inactifs</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Adhérents qui n'ont jamais emprunté</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Documents jamais prêtés</a></li>
	</ul>


	<h5>Autres</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Exemplaires perdus</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalogue par type de document</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">Prêts par catégorie d'adhérent</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Durée moyenne du prêt</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Etat de caisse</a></li>
	</ul>
