<h5>Systemeinstellungen</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">Systemeinstellungen</a></li>
</ul>

<h5>Basisparameter</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">Bibliotheken, Zweigstellen, Gruppen</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Fonds und Etats</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">Währungen und Wechselkurse</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">Medientypen und Ausleihcodes</a></li>
</ul>

<h5>Benutzer und Ausleihe</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">Benutzertyp und -kategorie</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">Städte</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">Wegtypen</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Benutzerattribute</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Ausleihbedingungen und Gebührenregelungen</a></li>
</ul>

<h5>Katalog</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">Autorisierte Werte</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">MARC bibliographisches Framework</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Koha zu MARC Mapping</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">MARC Test bibliographisches Framework</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">Normdatentypen</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">Klassifikationsquellen</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">Datensatz-Übereinstimmungsregeln</a></li>
</ul>

<h5>Weitere Parameter</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/stopwords.pl">Stopwörter</a></li>
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 Clientprofile</a></li>
</ul>
