<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Start</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Katalog</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Benutzer</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Erwerbungen</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Ausleihe</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Berichte</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parameter</a> ||
<a href="/cgi-bin/koha/about.pl">Über Koha</a> || 
Hilfe
</div>

</body>
</html>
