<h5>Reports anlegen und ausführen</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">Neuen anlegen</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">Nutze gespeicherte</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">aus SQL erstellen</a></li>
</ul>
<h5>Reports Wörterbuch</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">Wörterbuch anzeigen</a></li>
</ul>