<form action="/cgi-bin/koha/edithelp.pl" method="post">
  <fieldset class="action"><input type="button" class="submit" onclick="window.close(); return false;" value="Hilfefenster schließen">
  <input type="hidden" name="type" value="modify" />
  <input type="hidden" name="referer" value="<!-- TMPL_VAR NAME="referer" -->" />
  <input type="submit" class="submit" value="Hilfe bearbeiten"></fieldset>
</form>
</body>
</html>
