<div id="navmenu"><ul id="navmenulist">
	<li><a href="/cgi-bin/koha/labels/label-home.pl">Layouts</a></li>
	<li><a href="/cgi-bin/koha/labels/label-templates.pl">Templates</a></li>
	<li><a href="/cgi-bin/koha/labels/label-profiles.pl">Druckerprofile</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=labels">Stapel verwalten</a></li>
	<li><a href="/cgi-bin/koha/labels/label-manager.pl?type=patroncards">Benutzerausweis-Stapel verwalten</a></li>
</ul>
</div>
