<h5>Geführte Reports</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Geführte Reports</a></li>
	</ul>

<h5>Statistik Wizards</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Erwerbungen</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Benutzer</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Katalog</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Ausleihe</a></li>
	</ul>


	<h5>Top Listen</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Benutzer mit dem meisten Ausleihen</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">am häufigsten ausgeliehene Medien</a></li>
	</ul>
	
	<h5>Inaktiv</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Benutzer ohne Ausleihen</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Exemplare ohne Ausleihen</a></li>
	</ul>


	<h5>Andere</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Vermißte Medien</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Nach Medientyp katalogisieren</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">Ausleihen per Kundenkategorien</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Durchschnittliche Leihdauer</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Bis zur Wiederaufnahme</a></li>
	</ul>
