    <fieldset>
    <legend>Coded Fields</legend>
    <p>
    <label>Аудитория</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Любой</option>
      <option value="aud:a">юношество, в общем</option>
      <option value="aud:b">pre-primary (0-5)</option>
      <option value="aud:c">Primary (5-8)</option>
      <option value="aud:d">ребенок (9-14)</option>
      <option value="aud:e">Для молодежи</option>
      <option value="aud:k">Совершеннолетний, почтительный</option>
      <option value="aud:m">Совершеннолетний, в общем</option>
      <option value="aud:u">Unknown</option>
    </select>
    </p>
    <p>
    <label>Печать</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >будь-який</option>
        <option value="Material-type:r">regular print</option>
        <option value="Material-type:d">большая печать</option>
        <option value="Material-type:e">газетный формат</option>
        <option value="Material-type:f">Braille or Moon script</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">hand-written</option>
        <option value="Material-type:i">мультимедиа</option>
        <option value="Material-type:j">мини-печать</option>
        <option value="Material-type:z">other form of textual material</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Любой</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">эссе</option>
            <option value="Literature-Code:d">юмор, сатира</option>
            <option value="Literature-Code:e">letters</option>
            <option value="Literature-Code:f">short stories</option>
            <option value="Literature-Code:g">поэзия</option>
            <option value="Literature-Code:h">speeches, oratory</option>
            <option value="Literature-Code:y">not a literary text</option>
            <option value="Literature-Code:z">multiple/other lit. forms</option>
    </select>
    </p>
        <p>
    <label>Биография</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Любой</option>
            <option value="Biography-code:y">Не биография</option>
            <option value="Biography-code:a">автобиография</option>
            <option value="Biography-code:b">биография персоны</option>
            <option value="Biography-code:c">биография колектива</option>
            <option value="Biography-code:d">contains biogr. data</option>
    </select>
        </p>
        <p>
    <label>Иллюстрация</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Любой</option>
            <option value="Illustration-Code:a">иллюстрации</option>
            <option value="Illustration-Code:b">карты</option>
            <option value="Illustration-Code:c">портреты</option>
            <option value="Illustration-Code:d">charts</option>
            <option value="Illustration-Code:e">plans</option>
            <option value="Illustration-Code:f">plates</option>
            <option value="Illustration-Code:g">музика</option>
            <option value="Illustration-Code:h">facsimiles</option>
            <option value="Illustration-Code:i">coats of arms</option>
            <option value="Illustration-Code:j">генеологические таблицы</option>
            <option value="Illustration-Code:k">forms</option>
            <option value="Illustration-Code:l">samples</option>
            <option value="Illustration-Code:m">звуковые записи</option>
            <option value="Illustration-Code:n">transparencies</option>
            <option value="Illustration-Code:o">illuminations</option>
            <option value="Illustration-Code:y">нет иллюстраций</option>
        </select>
        </p>
    <p>
    <label>Content</label>
    <select name="limit" class="subtype">
      <option value="" >Любой</option>
            <option value="ctype:a" >bibliography</option>
            <option value="ctype:b" >каталог</option>
            <option value="ctype:c" >index</option>
            <option value="ctype:d" >abstract</option>
            <option value="ctype:e" >словарь</option>
            <option value="ctype:f" >энциклопедия</option>
            <option value="ctype:g" >directory</option>
            <option value="ctype:h" >project description</option>
            <option value="ctype:i" >statistics</option>
            <option value="ctype:j" >programmed text books</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >dissertation or thesis</option>
            <option value="ctype:n" >законы и законодательство</option>
            <option value="ctype:o" >numeric table</option>
            <option value="ctype:p" >технический отчет</option>
            <option value="ctype:q" >examination paper</option>
            <option value="ctype:r" >literature surveys/reviews</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >cartoons or comic strips</option>
            <option value="ctype:z" >other</option>
    </select>
        </p>
        <p>
    <label>Video Types</label>
    <select name="limit" class="subtype">
            <option value="">Любой</option>
      <option value="Video-mt:a">motion picture</option>
      <option value="Video-mt:b">visual projection</option>
      <option value="Video-mt:c">видео-запись</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Сериальные издания</legend><p>
    <p>
    <label>Serial Type</label>
    <select name="limit" class="subtype">
           <option value="">Any type</option>
           <option value="Type-Of-Serial:a">Периодическое издание</option>
      <option value="Type-Of-Serial:b">Монографические серии</option>
      <option value="Type-Of-Serial:c">Газета</option>
      <option value="Type-Of-Serial:z">Other</option>
    </select>
    </p>
    <p>
    <label>Периодичность</label>
    <select name="limit" class="subtype">
      <option value="">Любой</option>
        <option value="Frequency-code:a">Ежедневно</option>
        <option value="Frequency-code:b">Semiweekly</option>
        <option value="Frequency-code:c">Weekly</option>
        <option value="Frequency-code:d">Biweekly</option>
        <option value="Frequency-code:e">Semimonthly</option>
        <option value="Frequency-code:f">Ежемесячник</option>
        <option value="Frequency-code:g">Bimonthly</option>
        <option value="Frequency-code:h">Ежеквартально</option>
        <option value="Frequency-code:i">Трижды в год</option>
        <option value="Frequency-code:j">Semiannual</option>
        <option value="Frequency-code:k">Annual</option>
        <option value="Frequency-code:l">Полугодичник</option>
        <option value="Frequency-code:m">Triennial</option>
        <option value="Frequency-code:n">Трижды в неделю</option>
        <option value="Frequency-code:o">Трижды в месяц</option>
        <option value="Frequency-code:u">Unknown</option>
        <option value="Frequency-code:y">Без периодичности</option>
        <option value="Frequency-code:i">Other</option>
    </select>
    </p>
    <p>
    <label>Регулярность</label>
    <select name="limit" class="subtype">
            <option value="">Any regularity</option>
        <option value="Regularity-code:u">Unknown</option>
        <option value="Regularity-code:a">Регулярно</option>
        <option value="Regularity-code:b">Normalised irregular</option>
        <option value="Regularity-code:y">irregular</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Изображение</legend><p>
    <select name="limit" class="subtype">
        <option value="">Любой</option>
        <option value="Graphics-type:a">коллаж</option>
        <option value="Graphics-type:b">drawing</option>
        <option value="Graphics-type:c">painting</option>
        <option value="Graphics-type:d">photomechanical reproduction</option>
        <option value="Graphics-type:e">photonegative</option>
        <option value="Graphics-type:f">photoprint</option>
        <option value="Graphics-type:h">picture</option>
        <option value="Graphics-type:i">print</option>
        <option value="Graphics-type:k">technical drawing</option>
        <option value="Graphics-type:z">other non-projected graphic type</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">будь-який</option>
            <option value="Graphics-support:a">canvas</option>
            <option value="Graphics-support:b">bristol board</option>
            <option value="Graphics-support:c">cardboard/illustration board</option>
            <option value="Graphics-support:d">стекло</option>
            <option value="Graphics-support:j">plaster</option>
            <option value="Graphics-support:k">hardboard</option>
            <option value="Graphics-support:l">фарфор</option>
            <option value="Graphics-support:m">камень</option>
            <option value="Graphics-support:n">дерево</option>
            <option value="Graphics-support:u">unknown</option>
            <option value="Graphics-support:v">mixed collection</option>
            <option value="Graphics-support:e">synthetics</option>
            <option value="Graphics-support:f">skin</option>
            <option value="Graphics-support:g">textile</option>
            <option value="Graphics-support:h">металл</option>
            <option value="Graphics-support:i">бумага</option>
            <option value="Graphics-support:z">others</option>
    </select>
        </p>
