<h5>Systeminnstillinger</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">Systeminnstillinger</a></li>
</ul>

<h5>Grunnleggende parametere</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">Biblioteker, filialer og grupper</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds and budgets</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">Valutaer og vekslingskurser</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">Materialtyper og utlånskoder</a></li>
</ul>

<h5>Patrons and circulation</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">Patron types and categories</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">Byer og tettsteder</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">Veityper</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Patron attribute types</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Circulation and fines rules</a></li>
</ul>

<h5>Samling</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">Godkjente verdier</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">MARC Bibliographic framework</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Koha to MARC mapping</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">MARC Bibliographic framework test</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">Kildetyper</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">Klassifiseringskilde</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">Record matching rules</a></li>
</ul>

<h5>Ekstraparametre</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/stopwords.pl">Stoppord</a></li>
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 Client Targets</a></li>
</ul>
