<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Home</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Samling</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Medlemmer</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Innkjøp</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Fjernlån</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Rapporter</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Parametre</a> ||
<a href="/cgi-bin/koha/about.pl">Om Koha</a> || 
Hjelp
</div>

</body>
</html>
