<h5>Lag og kjør rapporter</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">Lag ny</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">Bruk lagret</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">Opprett fra SQL</a></li>
</ul>
<h5>Reports Dictionary</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">Vis ordbok</a></li>
</ul>