<h5>Veiledede rapporter</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Veiledede rapporter</a></li>
	</ul>

<h5>Statistikkveivisere</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Innkjøp</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Patrons</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Samling</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Fjernlån</a></li>
	</ul>


	<h5>Top Lists</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Patrons with the most checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-Circulated Items</a></li>
	</ul>
	
	<h5>Ikke i bruk</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Patrons who haven't checked out</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items with no checkouts</a></li>
	</ul>


	<h5>Andre</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Tapte eksemplarer</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Samling etter materialtyper</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">Utlån fordelt på lånerkategori</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Gjennomsnittlig lånetid</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Till Reconciliation</a></li>
	</ul>
