    <fieldset>
    <legend>Codierte Felder</legend>
    <p>
    <label>Zielpublikum</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Beliebig</option>
      <option value="aud:a">Jugendlicher, allgemein</option>
      <option value="aud:b">Kleinkind (0-5)</option>
      <option value="aud:c">Kinder (5-8)</option>
      <option value="aud:d">Kinder (9-14)</option>
      <option value="aud:e">Jugendlicher</option>
      <option value="aud:k">Erwachsene, ernst</option>
      <option value="aud:m">Erwachsene, Allgemein</option>
      <option value="aud:u">unbekannt</option>
    </select>
    </p>
    <p>
    <label>Drucken</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >beliebig</option>
        <option value="Material-type:r">Normaldruck</option>
        <option value="Material-type:d">Großdruck</option>
        <option value="Material-type:e">Zeitungsformat</option>
        <option value="Material-type:f">Braille oder Moon</option>
        <option value="Material-type:g">Mikrodruck</option>
        <option value="Material-type:h">handgeschrieben</option>
        <option value="Material-type:i">Multimedia</option>
        <option value="Material-type:j">Kleindruck</option>
        <option value="Material-type:z">andere Form geschriebenen Materials</option>
    </select>
    </p>
    <p>
    <label>Festschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Beliebig</option>
            <option value="Literature-Code:a">Belletristik</option>
            <option value="Literature-Code:b">Drama</option>
            <option value="Literature-Code:c">Aufsätze</option>
            <option value="Literature-Code:d">Humor, Satire</option>
            <option value="Literature-Code:e">Briefe</option>
            <option value="Literature-Code:f">Kurzgeschichten</option>
            <option value="Literature-Code:g">Poesie</option>
            <option value="Literature-Code:h">Reden</option>
            <option value="Literature-Code:y">kein literarischer Text</option>
            <option value="Literature-Code:z">verschiedene/andere lit. Formen</option>
    </select>
    </p>
        <p>
    <label>Biografie</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Beliebig</option>
            <option value="Biography-code:y">Keine Biografie</option>
            <option value="Biography-code:a">Autobiographie</option>
            <option value="Biography-code:b">Einzelbiographie</option>
            <option value="Biography-code:c">Gemeinschaftsbiographie</option>
            <option value="Biography-code:d">enthält biogr. Daten</option>
    </select>
        </p>
        <p>
    <label>Illustration</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Beliebig</option>
            <option value="Illustration-Code:a">Illustrationen</option>
            <option value="Illustration-Code:b">(Land-)Karten</option>
            <option value="Illustration-Code:c">Porträts</option>
            <option value="Illustration-Code:d">Charts</option>
            <option value="Illustration-Code:e">Pläne</option>
            <option value="Illustration-Code:f">Bildtafeln</option>
            <option value="Illustration-Code:g">Musik</option>
            <option value="Illustration-Code:h">Faksimile</option>
            <option value="Illustration-Code:i">Wappen</option>
            <option value="Illustration-Code:j">Ahnentafeln</option>
            <option value="Illustration-Code:k">Formulare</option>
            <option value="Illustration-Code:l">Muster</option>
            <option value="Illustration-Code:m">Tonträger</option>
            <option value="Illustration-Code:n">Folien</option>
            <option value="Illustration-Code:o">Buchmalereien</option>
            <option value="Illustration-Code:y">keine Illustrationen</option>
        </select>
        </p>
    <p>
    <label>Inhalt</label>
    <select name="limit" class="subtype">
      <option value="" >Beliebig</option>
            <option value="ctype:a" >Bibliographie</option>
            <option value="ctype:b" >Katalog</option>
            <option value="ctype:c" >indizieren</option>
            <option value="ctype:d" >Zusammenfassung</option>
            <option value="ctype:e" >Wörterbuch</option>
            <option value="ctype:f" >Enzyklopädie</option>
            <option value="ctype:g" >Verzeichnis</option>
            <option value="ctype:h" >Projektbeschreibung</option>
            <option value="ctype:i" >Statistiken</option>
            <option value="ctype:j" >Bücher für programmiertes Lernen</option>
            <option value="ctype:k" >Patent</option>
            <option value="ctype:l" >Standard</option>
            <option value="ctype:m" >Dissertationen oder Abschlussarbeiten</option>
            <option value="ctype:n" >Recht und Gesetze</option>
            <option value="ctype:o" >nummerische Tabelle</option>
            <option value="ctype:p" >technische Dokumentation</option>
            <option value="ctype:q" >Prüfungsarbeit</option>
            <option value="ctype:r" >Literaturübersicht/Besprechungen</option>
            <option value="ctype:s" >Verträge</option>
            <option value="ctype:t" >Cartoon oder Comic</option>
            <option value="ctype:z" >anderer</option>
    </select>
        </p>
        <p>
    <label>Videotypen</label>
    <select name="limit" class="subtype">
            <option value="">Beliebig</option>
      <option value="Video-mt:a">Film</option>
      <option value="Video-mt:b">optische Projektion</option>
      <option value="Video-mt:c">Videoaufnahme</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Zeitschriften</legend><p>
    <p>
    <label>Zeitschriftentyp</label>
    <select name="limit" class="subtype">
           <option value="">Beliebiger Typ</option>
           <option value="Type-Of-Serial:a">periodisch</option>
      <option value="Type-Of-Serial:b">Monographien</option>
      <option value="Type-Of-Serial:c">Zeitung</option>
      <option value="Type-Of-Serial:z">andere</option>
    </select>
    </p>
    <p>
    <label>Periodizität</label>
    <select name="limit" class="subtype">
      <option value="">Beliebig</option>
        <option value="Frequency-code:a">Täglich</option>
        <option value="Frequency-code:b">halbwöchentlich</option>
        <option value="Frequency-code:c">Wöchentlich</option>
        <option value="Frequency-code:d">Vierzehntägig</option>
        <option value="Frequency-code:e">Halbmonatlich</option>
        <option value="Frequency-code:f">monatlich</option>
        <option value="Frequency-code:g">Zweimonatlich </option>
        <option value="Frequency-code:h">Vierteljährlich</option>
        <option value="Frequency-code:i">dreimal pro Jahr</option>
        <option value="Frequency-code:j">halbjährlich</option>
        <option value="Frequency-code:k">Jährlich</option>
        <option value="Frequency-code:l">Zweijährlich</option>
        <option value="Frequency-code:m">Dreijährlich</option>
        <option value="Frequency-code:n">dreimal pro Woche</option>
        <option value="Frequency-code:o">dreimal pro Monat</option>
        <option value="Frequency-code:u">unbekannt</option>
        <option value="Frequency-code:y">unregelmäßig</option>
        <option value="Frequency-code:i">andere</option>
    </select>
    </p>
    <p>
    <label>Ordnung</label>
    <select name="limit" class="subtype">
            <option value="">Beliebige Ordnung</option>
        <option value="Regularity-code:u">unbekannt</option>
        <option value="Regularity-code:a">Regelmässig</option>
        <option value="Regularity-code:b">irregulär normaisiert</option>
        <option value="Regularity-code:y">irregulär</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Bild</legend><p>
    <select name="limit" class="subtype">
        <option value="">Beliebig</option>
        <option value="Graphics-type:a">Collage</option>
        <option value="Graphics-type:b">Gemälde</option>
        <option value="Graphics-type:c">Gemälde</option>
        <option value="Graphics-type:d">Fotomechanische Reproduktion (Kopie)</option>
        <option value="Graphics-type:e">Fotonegativ</option>
        <option value="Graphics-type:f">Fotodruck</option>
        <option value="Graphics-type:h">Bild</option>
        <option value="Graphics-type:i">Druck</option>
        <option value="Graphics-type:k">technische Zeichnungen</option>
        <option value="Graphics-type:z">anderer nicht-projizierter Grafiktyp</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">beliebig</option>
            <option value="Graphics-support:a">Leinwand</option>
            <option value="Graphics-support:b">Zeichenkarton</option>
            <option value="Graphics-support:c">Kunstdruck/Aquarell</option>
            <option value="Graphics-support:d">Glas</option>
            <option value="Graphics-support:j">Gips</option>
            <option value="Graphics-support:k">Hartplatte</option>
            <option value="Graphics-support:l">Porzellan</option>
            <option value="Graphics-support:m">Stein</option>
            <option value="Graphics-support:n">Holz</option>
            <option value="Graphics-support:u">unbekannt</option>
            <option value="Graphics-support:v">gemischte Sammlung</option>
            <option value="Graphics-support:e">synthetische Materialien</option>
            <option value="Graphics-support:f">Oberfläche</option>
            <option value="Graphics-support:g">Textilien</option>
            <option value="Graphics-support:h">Metall</option>
            <option value="Graphics-support:i">Papier</option>
            <option value="Graphics-support:z">andere</option>
    </select>
        </p>
