<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Начало</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Каталог</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Посетители</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Поступление</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Оборот</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Отчеты</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Параметры</a> ||
<a href="/cgi-bin/koha/about.pl">Про АБИС Коха</a> || 
Помощь
</div>

</body>
</html>
