<h5>Guided Reports</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Guided Reports</a></li>
	</ul>

<h5>Statistics wizards</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Поступление</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Посетители</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Каталог</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Оборот</a></li>
	</ul>


	<h5>Верхние места</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Patrons with the most checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-Circulated Items</a></li>
	</ul>
	
	<h5>Незадействовано</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Patrons who haven't checked out</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items with no checkouts</a></li>
	</ul>


	<h5>Other</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Lost Items</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Каталог за типами единиц хранения</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">Checkouts by patron category</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Среднее время ссуды</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Till Reconciliation</a></li>
	</ul>
