<h5>مفضلات النظام</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">مفضلات النظام</a></li>
</ul>

<h5>عوامل أساسية</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">المكتبات,الفروع, المجموعات</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Funds and budgets</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">عملات وأسعار صرف""</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">أنواع المادة ورموز الاعارة</a></li>
</ul>

<h5>المستخدمين والاعارة</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">أنواع و فئات مستخدم</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl"> مدن وبلدان</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">أنواع الطريق</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Patron attribute types</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Circulation and fines rules</a></li>
</ul>

<h5>الفهرس</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">قيم محققة</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">إطار مارك للبيانات الببليوجرافية</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">نخطيط مارك لكوها</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">إختبار إطار مارك للبيانات الببليوجرافية</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">انواع الاستناد</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">مصدر التصنيف</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">"قواعد مضاهاة التسجيلة"</a></li>
</ul>

<h5>عوامل إضافية</h5>

<ul>
	<li><a href="/cgi-bin/koha/admin/stopwords.pl">كلمات توقف</a></li>
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Z39.50 هدف عميل </a></li>
</ul>
