<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">رئيسى</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">الفهرس</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">الاعضاء</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">التزويد</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">الاعارة</a> ||
<a href="/cgi-bin/koha/reports-home.pl">تقارير</a> ||
<a href="/cgi-bin/koha/admin-home.pl">مؤشرات</a> ||
<a href="/cgi-bin/koha/about.pl">حول كوها</a> || 
مساعدة
</div>

</body>
</html>
