<h5>أنشئ و شغّل تقارير</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build new">إنشئ جديد</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Used saved">الاستخدام حفظ</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create report from SQL">إنشئ من SQL </a></li>
</ul>
<h5>قاموس التقارير</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View Dictionary">إعرض القاموس</a></li>
</ul>