<h5>التقارير المرشدة</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">التقارير المرشدة</a></li>
	</ul>

<h5>معالجات الاحصائيات</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">التزويد</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">مستخدمين</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">الفهرس</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">الاعارة</a></li>
	</ul>


	<h5>القوائم العليا</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Patrons with the most checkouts</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-Circulated Items</a></li>
	</ul>
	
	<h5>خامل</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">المستفيد الذي ليس لديه أي إعارات</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">مواد بدون إعارات</a></li>
	</ul>


	<h5>آخر</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">مواد مفقودة</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalogue by Item Type</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=issues_by_borrower_category">إعارات حسب فئه المستخدم</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">متوسط وقت الإعارة</a></li>
		<li><a href="/cgi-bin/koha/reports/stats.screen.pl">Till Reconciliation</a></li>
	</ul>
