<select name="idx">
<!-- TMPL_IF NAME="selected" --><option value="kw" selected="selected">الكلمة المفتاحية</option><!-- TMPL_ELSE --><option value="kw">الكلمة المفتاحية</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,wrdl" selected="selected">مؤلف</option><!-- TMPL_ELSE --><option value="au">مؤلف</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="au,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Author as Phrase</option><!-- TMPL_ELSE --><option value="au,phr">&nbsp;&nbsp;&nbsp;&nbsp; Author as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; اسم جامع</option><!-- TMPL_ELSE --><option value="cpn">&nbsp;&nbsp;&nbsp;&nbsp; اسم جامع</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,wrdl" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; اسم مؤتمر</option><!-- TMPL_ELSE --><option value="cfn">&nbsp;&nbsp;&nbsp;&nbsp; اسم مؤتمر</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cpn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Corporate Name as Phrase</option><!-- TMPL_ELSE --><option value="cpn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Corporate Name as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="cfn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Conference Name as Phrase</option><!-- TMPL_ELSE --><option value="cfn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Conference Name as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; اسم شخصى</option><!-- TMPL_ELSE --><option value="pn">&nbsp;&nbsp;&nbsp;&nbsp; اسم شخصى</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Personal Name as Phrase</option><!-- TMPL_ELSE --><option value="pn,phr">&nbsp;&nbsp;&nbsp;&nbsp; Personal Name as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ln" selected="selected">اللغة</option><!-- TMPL_ELSE --><option value="ln">اللغة</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nt" selected="selected">ملاحظات/تعليقات</option><!-- TMPL_ELSE --><option value="nt">ملاحظات/تعليقات</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pb" selected="selected">الناشر</option><!-- TMPL_ELSE --><option value="pb">الناشر</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="pl" selected="selected">موقع الناشر</option><!-- TMPL_ELSE --><option value="pl">موقع الناشر</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="yr" selected="selected">Publication Date (yyyy)</option><!-- TMPL_ELSE --><option value="yr">Publication Date (yyyy)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="acqdate" selected="selected">Acquisition Date (yyyy-mm-dd)</option><!-- TMPL_ELSE --><option value="acqdate">Acquisition Date (yyyy-mm-dd)</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="sn" selected="selected">رقم معيارى</option><!-- TMPL_ELSE --><option value="sn">رقم معيارى</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="nb" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; تدمك</option><!-- TMPL_ELSE --><option value="nb">&nbsp;&nbsp;&nbsp;&nbsp; تدمك</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ns" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; تدمد</option><!-- TMPL_ELSE --><option value="ns">&nbsp;&nbsp;&nbsp;&nbsp; تدمد</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="lcn,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp;رقم الطلب</option><!-- TMPL_ELSE --><option value="lcn,phr">&nbsp;&nbsp;&nbsp;&nbsp;رقم الطلب</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su" selected="selected">موضوع</option><!-- TMPL_ELSE --><option value="su">موضوع</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="su,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Subject as Phrase</option><!-- TMPL_ELSE --><option value="su,phr">&nbsp;&nbsp;&nbsp;&nbsp; Subject as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti" selected="selected">عنوان</option><!-- TMPL_ELSE --><option value="ti">عنوان</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="ti,phr" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; Title as Phrase</option><!-- TMPL_ELSE --><option value="ti,phr">&nbsp;&nbsp;&nbsp;&nbsp; Title as Phrase</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="se" selected="selected">&nbsp;&nbsp;&nbsp;&nbsp; عنوان سلسلة</option><!-- TMPL_ELSE --><option value="se">&nbsp;&nbsp;&nbsp;&nbsp; عنوان سلسلة</option><!-- /TMPL_IF -->

<!-- TMPL_IF NAME="selected" --><option value="bc" selected="selected">الباركود</option><!-- TMPL_ELSE --><option value="bc">الباركود</option>
<!-- /TMPL_IF -->
</select>
