    <fieldset>
    <legend>Kodede felter</legend>
    <p>
    <label>Publikum</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Alle</option>
      <option value="aud:a">ungdom, generelt</option>
      <option value="aud:b">småbarn (0&ndash;5)</option>
      <option value="aud:c">Førsteprioritet (5-8)</option>
      <option value="aud:d">barn (9&ndash;14)</option>
      <option value="aud:e">Ung voksen</option>
      <option value="aud:k">Voksen, alvorlig</option>
      <option value="aud:m">Voksen, generelt</option>
      <option value="aud:u">Ukjent</option>
    </select>
    </p>
    <p>
    <label>Skriv ut</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >any</option>
        <option value="Material-type:r">vanlig trykk</option>
        <option value="Material-type:d">stor skrift</option>
        <option value="Material-type:e">avisformat</option>
        <option value="Material-type:f">Blindeskrift eller måneskrift</option>
        <option value="Material-type:g">microprint</option>
        <option value="Material-type:h">håndskrevet</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-print</option>
        <option value="Material-type:z">andre typer tekstmateriale</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Alle</option>
            <option value="Literature-Code:a">skjønnlitteratur</option>
            <option value="Literature-Code:b">skuespill</option>
            <option value="Literature-Code:c">essay</option>
            <option value="Literature-Code:d">humor, satire</option>
            <option value="Literature-Code:e">brev</option>
            <option value="Literature-Code:f">noveller</option>
            <option value="Literature-Code:g">poesi</option>
            <option value="Literature-Code:h">taler, lydmateriale</option>
            <option value="Literature-Code:y">ikke en litterær tekst</option>
            <option value="Literature-Code:z">flere eller andre litterære sjangere</option>
    </select>
    </p>
        <p>
    <label>Biografi</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Alle</option>
            <option value="Biography-code:y">Ikke en biografi</option>
            <option value="Biography-code:a">selvbiografi</option>
            <option value="Biography-code:b">individuell biografi</option>
            <option value="Biography-code:c">samlebiografi</option>
            <option value="Biography-code:d">inneholder biografisk informasjon</option>
    </select>
        </p>
        <p>
    <label>Illustrasjon</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Alle</option>
            <option value="Illustration-Code:a">illustrasjoner</option>
            <option value="Illustration-Code:b">kart</option>
            <option value="Illustration-Code:c">portretter</option>
            <option value="Illustration-Code:d">diagrammer</option>
            <option value="Illustration-Code:e">grunnriss</option>
            <option value="Illustration-Code:f">plater</option>
            <option value="Illustration-Code:g">musikk</option>
            <option value="Illustration-Code:h">faksimiler</option>
            <option value="Illustration-Code:i">våpenskjold</option>
            <option value="Illustration-Code:j">slektstavler</option>
            <option value="Illustration-Code:k">skjemaer</option>
            <option value="Illustration-Code:l">samples</option>
            <option value="Illustration-Code:m">lydopptak</option>
            <option value="Illustration-Code:n">transparenter</option>
            <option value="Illustration-Code:o">illuminations</option>
            <option value="Illustration-Code:y">uten illustrasjoner</option>
        </select>
        </p>
    <p>
    <label>Innhold</label>
    <select name="limit" class="subtype">
      <option value="" >Alle</option>
            <option value="ctype:a" >bibliografi</option>
            <option value="ctype:b" >samling</option>
            <option value="ctype:c" >register</option>
            <option value="ctype:d" >sammendrag</option>
            <option value="ctype:e" >ordbok</option>
            <option value="ctype:f" >leksikon</option>
            <option value="ctype:g" >mappe</option>
            <option value="ctype:h" >prosjektbeskrivelse</option>
            <option value="ctype:i" >satistikk</option>
            <option value="ctype:j" >programmed text books</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >avhandling eller oppgave</option>
            <option value="ctype:n" >lovtekster og lovgivning</option>
            <option value="ctype:o" >numerisk tabell</option>
            <option value="ctype:p" >teknisk rapport</option>
            <option value="ctype:q" >eksamensoppgaver</option>
            <option value="ctype:r" >literature surveys/reviews</option>
            <option value="ctype:s" >traktater</option>
            <option value="ctype:t" >tegneserier</option>
            <option value="ctype:z" >andre</option>
    </select>
        </p>
        <p>
    <label>Videotyper</label>
    <select name="limit" class="subtype">
            <option value="">Alle</option>
      <option value="Video-mt:a">bevegelig bilde</option>
      <option value="Video-mt:b">visuelle projeksjoner</option>
      <option value="Video-mt:c">videoopptak</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Periodikaer</legend><p>
    <p>
    <label>Periodikatype</label>
    <select name="limit" class="subtype">
           <option value="">Alle slag</option>
           <option value="Type-Of-Serial:a">Tidsskrift og aviser</option>
      <option value="Type-Of-Serial:b">Monografiserie</option>
      <option value="Type-Of-Serial:c">Avis</option>
      <option value="Type-Of-Serial:z">Andre</option>
    </select>
    </p>
    <p>
    <label>Oppgitt utgivelsesfrekvens</label>
    <select name="limit" class="subtype">
      <option value="">Alle</option>
        <option value="Frequency-code:a">Daglig</option>
        <option value="Frequency-code:b">To ganger i uka</option>
        <option value="Frequency-code:c">Ukentlig</option>
        <option value="Frequency-code:d">Annenhver uke</option>
        <option value="Frequency-code:e">To ganger i måneden</option>
        <option value="Frequency-code:f">Månedlig</option>
        <option value="Frequency-code:g">Annenhver måned</option>
        <option value="Frequency-code:h">Kvartalsvis</option>
        <option value="Frequency-code:i">Tre ganger per år</option>
        <option value="Frequency-code:j">Hvert halvår</option>
        <option value="Frequency-code:k">Årlig</option>
        <option value="Frequency-code:l">Annethvert år</option>
        <option value="Frequency-code:m">Hvert tredje år</option>
        <option value="Frequency-code:n">Tre ganger i uka</option>
        <option value="Frequency-code:o">Tre ganger i måneden</option>
        <option value="Frequency-code:u">Ukjent</option>
        <option value="Frequency-code:y">Fullstendig uregelmessig</option>
        <option value="Frequency-code:i">Andre</option>
    </select>
    </p>
    <p>
    <label>Faktisk utgivelsesmønster</label>
    <select name="limit" class="subtype">
            <option value="">Alle faktiske utgivelsesmønstre</option>
        <option value="Regularity-code:u">Ukjent</option>
        <option value="Regularity-code:a">Vanlig</option>
        <option value="Regularity-code:b">Normalisert uregelmessig</option>
        <option value="Regularity-code:y">uregelmessig</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Bilde</legend><p>
    <select name="limit" class="subtype">
        <option value="">Alle</option>
        <option value="Graphics-type:a">kollasj</option>
        <option value="Graphics-type:b">tegning</option>
        <option value="Graphics-type:c">maleri</option>
        <option value="Graphics-type:d">fotomekanisk reproduksjon</option>
        <option value="Graphics-type:e">bildenegativ</option>
        <option value="Graphics-type:f">bildetrykk</option>
        <option value="Graphics-type:h">bilde</option>
        <option value="Graphics-type:i">trykk</option>
        <option value="Graphics-type:k">teknisk tegning</option>
        <option value="Graphics-type:z">other non-projected graphic type</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">any</option>
            <option value="Graphics-support:a">lerret</option>
            <option value="Graphics-support:b">Bristol-papir</option>
            <option value="Graphics-support:c">cardboard/illustration board</option>
            <option value="Graphics-support:d">glass</option>
            <option value="Graphics-support:j">gips</option>
            <option value="Graphics-support:k">sponplate</option>
            <option value="Graphics-support:l">porselen</option>
            <option value="Graphics-support:m">stein</option>
            <option value="Graphics-support:n">tre</option>
            <option value="Graphics-support:u">ukjent</option>
            <option value="Graphics-support:v">blandede samlinger</option>
            <option value="Graphics-support:e">syntetisk</option>
            <option value="Graphics-support:f">skinn</option>
            <option value="Graphics-support:g">tekstil</option>
            <option value="Graphics-support:h">metall</option>
            <option value="Graphics-support:i">papir</option>
            <option value="Graphics-support:z">annet</option>
    </select>
        </p>
