    <fieldset>
    <legend>代碼欄位</legend>
    <p>
    <label>讀者對象</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >任何</option>
      <option value="aud:a">青少年，一般性</option>
      <option value="aud:b">學前兒童，0-5 歲</option>
      <option value="aud:c">學前兒童，（5-8歲）</option>
      <option value="aud:d">兒童，9-14 歲</option>
      <option value="aud:e">青少年，14-20 歲</option>
      <option value="aud:k">成人，學術性</option>
      <option value="aud:m">成人，一般性</option>
      <option value="aud:u">不詳</option>
    </select>
    </p>
    <p>
    <label>列印</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >任何</option>
        <option value="Material-type:r">一般印刷資料</option>
        <option value="Material-type:d">大字體印刷資料</option>
        <option value="Material-type:e">報紙形式</option>
        <option value="Material-type:f">點字本</option>
        <option value="Material-type:g">微縮資料</option>
        <option value="Material-type:h">手稿</option>
        <option value="Material-type:i">多媒體</option>
        <option value="Material-type:j">縮印資料</option>
        <option value="Material-type:z">其他</option>
    </select>
    </p>
    <p>
    <label>文學體裁</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >任何</option>
            <option value="Literature-Code:a">小說</option>
            <option value="Literature-Code:b">戲劇（包括電視劇、電影劇本）</option>
            <option value="Literature-Code:c">散文（小品、雜文、駢文）</option>
            <option value="Literature-Code:d">幽默(humor)；諷刺文(satire)</option>
            <option value="Literature-Code:e">書信</option>
            <option value="Literature-Code:f">短篇故事、民間故事、寓言、神話、童話、傳說</option>
            <option value="Literature-Code:g">詩詞、曲、賦、歌謠</option>
            <option value="Literature-Code:h">演說稿、對話錄</option>
            <option value="Literature-Code:y">非文學作品</option>
            <option value="Literature-Code:z">其他或多種體裁（例如：遊記、傳記、報導文學、對聯）</option>
    </select>
    </p>
        <p>
    <label>傳記</label>
        <select name="limit" class="subtype" size="1">
            <option value="">任何</option>
            <option value="Biography-code:y">不是傳記</option>
            <option value="Biography-code:a">自傳</option>
            <option value="Biography-code:b">分傳</option>
            <option value="Biography-code:c">總傳</option>
            <option value="Biography-code:d">包含傳記資料</option>
    </select>
        </p>
        <p>
    <label>插圖</label>
        <select name="limit" class="subtype" size="1">
            <option value="">任何</option>
            <option value="Illustration-Code:a">圖</option>
            <option value="Illustration-Code:b">地圖</option>
            <option value="Illustration-Code:c">肖像</option>
            <option value="Illustration-Code:d">航行圖</option>
            <option value="Illustration-Code:e">設計圖</option>
            <option value="Illustration-Code:f">圖版</option>
            <option value="Illustration-Code:g">音樂</option>
            <option value="Illustration-Code:h">影鈔；書影</option>
            <option value="Illustration-Code:i">徽章</option>
            <option value="Illustration-Code:j">譜系表</option>
            <option value="Illustration-Code:k">表格</option>
            <option value="Illustration-Code:l">標準（技術規範）</option>
            <option value="Illustration-Code:m">樂譜資料</option>
            <option value="Illustration-Code:n">透明圖片（如附在書袋中的透明片）</option>
            <option value="Illustration-Code:o">彩飾</option>
            <option value="Illustration-Code:y">無插圖</option>
        </select>
        </p>
    <p>
    <label>內容</label>
    <select name="limit" class="subtype">
      <option value="" >任何</option>
            <option value="ctype:a" >書目（如專科書目）</option>
            <option value="ctype:b" >目錄（器物目錄、藏書目錄、出版目錄、展覽目錄等）</option>
            <option value="ctype:c" >索引</option>
            <option value="ctype:d" >摘要</option>
            <option value="ctype:e" >字典查詢</option>
            <option value="ctype:f" >百科全書、類書</option>
            <option value="ctype:g" >名錄、指南</option>
            <option value="ctype:h" >專案計畫</option>
            <option value="ctype:i" >統計資料</option>
            <option value="ctype:j" >編序教材</option>
            <option value="ctype:k" >專利</option>
            <option value="ctype:l" >標準（技術規範）</option>
            <option value="ctype:m" >博士論文（dissertation）或是碩士論文（thesis）</option>
            <option value="ctype:n" >法規</option>
            <option value="ctype:o" >數值表</option>
            <option value="ctype:p" >技術報告</option>
            <option value="ctype:q" >試題</option>
            <option value="ctype:r" >文獻評析</option>
            <option value="ctype:s" >條約、協定</option>
            <option value="ctype:t" >漫畫、連環圖書</option>
            <option value="ctype:z" >其他</option>
    </select>
        </p>
        <p>
    <label>錄影資料規格</label>
    <select name="limit" class="subtype">
            <option value="">任何</option>
      <option value="Video-mt:a">電影片</option>
      <option value="Video-mt:b">投影資料</option>
      <option value="Video-mt:c">錄影帶</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>叢書：</legend><p>
    <p>
    <label>叢書型式：</label>
    <select name="limit" class="subtype">
           <option value="">任何資料類型</option>
           <option value="Type-Of-Serial:a">期刊</option>
      <option value="Type-Of-Serial:b">專題論文期刊</option>
      <option value="Type-Of-Serial:c">報紙</option>
      <option value="Type-Of-Serial:z">其他</option>
    </select>
    </p>
    <p>
    <label>期刊</label>
    <select name="limit" class="subtype">
      <option value="">任何</option>
        <option value="Frequency-code:a">日記</option>
        <option value="Frequency-code:b">半週刊</option>
        <option value="Frequency-code:c">週刊</option>
        <option value="Frequency-code:d">雙週刊</option>
        <option value="Frequency-code:e">半月刊</option>
        <option value="Frequency-code:f">月刊</option>
        <option value="Frequency-code:g">雙月刊</option>
        <option value="Frequency-code:h">季刊</option>
        <option value="Frequency-code:i">一年三次</option>
        <option value="Frequency-code:j">半年刊</option>
        <option value="Frequency-code:k">年刊</option>
        <option value="Frequency-code:l">雙年刊</option>
        <option value="Frequency-code:m">三年刊</option>
        <option value="Frequency-code:n">一週三次</option>
        <option value="Frequency-code:o">一月三次</option>
        <option value="Frequency-code:u">不詳</option>
        <option value="Frequency-code:y">不定期</option>
        <option value="Frequency-code:i">其他</option>
    </select>
    </p>
    <p>
    <label>規則性</label>
    <select name="limit" class="subtype">
            <option value="">任何規則</option>
        <option value="Regularity-code:u">不詳</option>
        <option value="Regularity-code:a">有規則</option>
        <option value="Regularity-code:b">定期性的不規則（如月刊，除7—8 月外）</option>
        <option value="Regularity-code:y">不規則</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>圖片</legend><p>
    <select name="limit" class="subtype">
        <option value="">任何</option>
        <option value="Graphics-type:a">拼貼</option>
        <option value="Graphics-type:b">素描</option>
        <option value="Graphics-type:c">繪畫</option>
        <option value="Graphics-type:d">照相複製品</option>
        <option value="Graphics-type:e">負片</option>
        <option value="Graphics-type:f">照片</option>
        <option value="Graphics-type:h">圖片</option>
        <option value="Graphics-type:i">列印</option>
        <option value="Graphics-type:k">工程圖</option>
        <option value="Graphics-type:z">其他非投影性平面作品</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">任何</option>
            <option value="Graphics-support:a">帆布</option>
            <option value="Graphics-support:b">布里斯托紙板</option>
            <option value="Graphics-support:c">紙板</option>
            <option value="Graphics-support:d">玻璃</option>
            <option value="Graphics-support:j">石膏</option>
            <option value="Graphics-support:k">夾板</option>
            <option value="Graphics-support:l">瓷器</option>
            <option value="Graphics-support:m">石頭</option>
            <option value="Graphics-support:n">木材</option>
            <option value="Graphics-support:u">不詳</option>
            <option value="Graphics-support:v">二種以上質料組成之基底</option>
            <option value="Graphics-support:e">合成品</option>
            <option value="Graphics-support:f">皮革（羊皮、牛皮等）</option>
            <option value="Graphics-support:g">紡織物</option>
            <option value="Graphics-support:h">金屬</option>
            <option value="Graphics-support:i">紙</option>
            <option value="Graphics-support:z">其他的</option>
    </select>
        </p>
