    <fieldset>
    <legend>Kódolt mezők</legend>
    <p>
    <label>Célközönség</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Bármelyik</option>
      <option value="aud:a">gyerek, általános</option>
      <option value="aud:b">elő-elemi (0-5)</option>
      <option value="aud:c">Elsődleges (5-8)</option>
      <option value="aud:d">gyerekek (9-14)</option>
      <option value="aud:e">Ifjúság</option>
      <option value="aud:k">Felnőtt</option>
      <option value="aud:m">Felnőtt, Általános</option>
      <option value="aud:u">Nem ismert</option>
    </select>
    </p>
    <p>
    <label>Nyomtat</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >bármely</option>
        <option value="Material-type:r">rendes betűméret</option>
        <option value="Material-type:d">nagy méretű betűvel nyomtatott</option>
        <option value="Material-type:e">újság forma</option>
        <option value="Material-type:f">Braille vagy Moon írás</option>
        <option value="Material-type:g">mikró-nyomtatvány</option>
        <option value="Material-type:h">kézzel írott</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-nyomtatvány</option>
        <option value="Material-type:z">más szöveges anyag</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Bármelyik</option>
            <option value="Literature-Code:a">fiction</option>
            <option value="Literature-Code:b">dráma</option>
            <option value="Literature-Code:c">essays</option>
            <option value="Literature-Code:d">humoros, szatirikus</option>
            <option value="Literature-Code:e">levelek</option>
            <option value="Literature-Code:f">elbeszélés, novella</option>
            <option value="Literature-Code:g">költészet</option>
            <option value="Literature-Code:h">beszédek, ékesszólások</option>
            <option value="Literature-Code:y">nem irodalmi szöveg</option>
            <option value="Literature-Code:z">összetett/égyéb irod. formák</option>
    </select>
    </p>
        <p>
    <label>Életrajz</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Bármelyik</option>
            <option value="Biography-code:y">Nem életrajz</option>
            <option value="Biography-code:a">önéletrajz</option>
            <option value="Biography-code:b">egyéni életrajz</option>
            <option value="Biography-code:c">közös életrajz</option>
            <option value="Biography-code:d">tartalmaz életrajzi adatot</option>
    </select>
        </p>
        <p>
    <label>Illusztráció</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Bármelyik</option>
            <option value="Illustration-Code:a">illusztráció</option>
            <option value="Illustration-Code:b">maps</option>
            <option value="Illustration-Code:c">portrét</option>
            <option value="Illustration-Code:d">ábrák</option>
            <option value="Illustration-Code:e">tervek</option>
            <option value="Illustration-Code:f">plates</option>
            <option value="Illustration-Code:g">zene</option>
            <option value="Illustration-Code:h">fakszimilé</option>
            <option value="Illustration-Code:i">címer</option>
            <option value="Illustration-Code:j">leszármazási tábla</option>
            <option value="Illustration-Code:k">forms</option>
            <option value="Illustration-Code:l">minta</option>
            <option value="Illustration-Code:m">sound recordings</option>
            <option value="Illustration-Code:n">dia</option>
            <option value="Illustration-Code:o">illuminált</option>
            <option value="Illustration-Code:y">nincs illusztráció</option>
        </select>
        </p>
    <p>
    <label>Content</label>
    <select name="limit" class="subtype">
      <option value="" >Bármelyik</option>
            <option value="ctype:a" >bibliográfia</option>
            <option value="ctype:b" >katalógus</option>
            <option value="ctype:c" >index</option>
            <option value="ctype:d" >kivonat</option>
            <option value="ctype:e" >dictionary</option>
            <option value="ctype:f" >enciklópédia</option>
            <option value="ctype:g" >címtár</option>
            <option value="ctype:h" >project description</option>
            <option value="ctype:i" >statisztika</option>
            <option value="ctype:j" >tankönyv</option>
            <option value="ctype:k" >patent</option>
            <option value="ctype:l" >standard</option>
            <option value="ctype:m" >disszertáció vagy tézis</option>
            <option value="ctype:n" >törvények és törvényhozás</option>
            <option value="ctype:o" >számszerű táblázat</option>
            <option value="ctype:p" >technikai riport</option>
            <option value="ctype:q" >vizsgadolgozat</option>
            <option value="ctype:r" >irodalmi szemlék</option>
            <option value="ctype:s" >treaties</option>
            <option value="ctype:t" >karikatúrák vagy képregények</option>
            <option value="ctype:z" >other</option>
    </select>
        </p>
        <p>
    <label>Video Types</label>
    <select name="limit" class="subtype">
            <option value="">Bármelyik</option>
      <option value="Video-mt:a">mozgó kép, film</option>
      <option value="Video-mt:b">vizuális projekció</option>
      <option value="Video-mt:c">videó felvételek</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Serials</legend><p>
    <p>
    <label>Serial Type</label>
    <select name="limit" class="subtype">
           <option value="">Any type</option>
           <option value="Type-Of-Serial:a">Időszaki</option>
      <option value="Type-Of-Serial:b">Monográfia sorozat</option>
      <option value="Type-Of-Serial:c">Újság</option>
      <option value="Type-Of-Serial:z">Más</option>
    </select>
    </p>
    <p>
    <label>Időszakos</label>
    <select name="limit" class="subtype">
      <option value="">Bármelyik</option>
        <option value="Frequency-code:a">Daily</option>
        <option value="Frequency-code:b">Kéthetente</option>
        <option value="Frequency-code:c">Weekly</option>
        <option value="Frequency-code:d">Biweekly</option>
        <option value="Frequency-code:e">Semimonthly</option>
        <option value="Frequency-code:f">Monthly</option>
        <option value="Frequency-code:g">Bimonthly</option>
        <option value="Frequency-code:h">Quarterly</option>
        <option value="Frequency-code:i">Háromszor per év</option>
        <option value="Frequency-code:j">Félévenkénti</option>
        <option value="Frequency-code:k">Évi</option>
        <option value="Frequency-code:l">Félévenkénti</option>
        <option value="Frequency-code:m">Triennal</option>
        <option value="Frequency-code:n">Háromszor per hét</option>
        <option value="Frequency-code:o">Háromszor per hónap</option>
        <option value="Frequency-code:u">Nem ismert</option>
        <option value="Frequency-code:y">Rendszertelen</option>
        <option value="Frequency-code:i">Más</option>
    </select>
    </p>
    <p>
    <label>Rendszeresség</label>
    <select name="limit" class="subtype">
            <option value="">Bármilyen gyakoriság</option>
        <option value="Regularity-code:u">Nem ismert</option>
        <option value="Regularity-code:a">Rendes</option>
        <option value="Regularity-code:b">Normalised irregular</option>
        <option value="Regularity-code:y">rendszertelen</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Kép</legend><p>
    <select name="limit" class="subtype">
        <option value="">Bármelyik</option>
        <option value="Graphics-type:a">kollázs</option>
        <option value="Graphics-type:b">rajz</option>
        <option value="Graphics-type:c">painting</option>
        <option value="Graphics-type:d">fotómechanikai reprodukció</option>
        <option value="Graphics-type:e">fotó negatív</option>
        <option value="Graphics-type:f">fotó-nyomtatvány</option>
        <option value="Graphics-type:h">kép</option>
        <option value="Graphics-type:i">print</option>
        <option value="Graphics-type:k">technikai rajz</option>
        <option value="Graphics-type:z">egyéb, nem tervezett grafikai típus</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">bármely</option>
            <option value="Graphics-support:a">vászon</option>
            <option value="Graphics-support:b">bristol board</option>
            <option value="Graphics-support:c">karton/ illusztrációs anyag</option>
            <option value="Graphics-support:d">üveg</option>
            <option value="Graphics-support:j">vakolat (?)</option>
            <option value="Graphics-support:k">kemény felületű</option>
            <option value="Graphics-support:l">porcelán</option>
            <option value="Graphics-support:m">kő</option>
            <option value="Graphics-support:n">fa</option>
            <option value="Graphics-support:u">Nem ismert</option>
            <option value="Graphics-support:v">mixed collection</option>
            <option value="Graphics-support:e">szintetikus</option>
            <option value="Graphics-support:f">skin</option>
            <option value="Graphics-support:g">textil</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">papír</option>
            <option value="Graphics-support:z">others</option>
    </select>
        </p>
